### ISSUE TITLE
Mismatching contexts on fi_recv and the rx CQ event

### ISSUE THREAD

**Issue by wavesoft** [ofiwg/libfabric#1826] opened 2016-03-04 10:45 UTC
Hello guys, this is probably related to #1693 , because some times I also see similar behavior. I am using the libfabric 2.0 release and I am using it through my nanomsg transport.

What I see when I run some tests, is that even though I am specifying a particular context in the `fi_send` function, it is not always correct on the `CQ` event. For instance, check the following output from my test app:
```
...
[002071725824] OFI[S]: Posting buffers for receiving handshake
[002071725824] OFI[i]: Blocking RX Post max_sz=4
[002071725824] OFI[i] ### POSTING RECEIVE BUFFER len=1024, ctx=0x7f94744f7920
...
[002071725824] OFI[S]: Receiving handshake
[002071725824] OFI[i]: Blocking RX Recv max_sz=4, timeout=1000
[002071725824] OFI[i]: Blocking RX Completed, len=4, ctx=0x7f94744f7920
...
[002071725824] OFI[i]: Posting buffers from RxMR chunk=0x7f9474000dd0 (ctx=0x7f9474000de8, buf=0x7f947cdc2038)
[002071725824] OFI[i] ### POSTING RECEIVE BUFFER len=131072, ctx=0x7f9474000de8
[002071725824] OFI[i]: Input buffers posted
...
[002038404864] OFI[p]: Rx CQ Event (ret=1, ctx=0x7f94744f7920)
[002038404864] OFI[i]: Got CQ event for the received frame, ctx=0x7f94744f7908 (ptr=0x7f94744f7920)
[002038404864] OFI[i]: Got incoming len=516, chunk=0x2
```
When you see a "POSTING RECEIVE BUFFER" message, the `fi_recv` function is about to be called, and the `ctx=` points to the context given to the function. Accordingly, on the Rx CQ event the `ctx=` points to the `[struct fi_cq_data_entry]->op_context`. 

What I can't understand is the fact that the context from the first `fi_recv` remains the same even after the second call to `fi_recv`! And of course this causes a segfault because the context pointer is invalid. 

---

It seems that I can consistently reproduce the problem, so you can try to reproduce the problem yourselves:

```shell
# Work in an isolated directory
mkdir bug; cd bug
BASEDIR=$(pwd)
# Prepare nanomsg
git clone https://github.com/wavesoft/nanomsg.git
cd nanomsg; ./autogen.sh; cd ..
# Apply OFI patch
git clone https://github.com/wavesoft/nanomsg-transport-ofi.git
cd nanomsg-transport-ofi; git checkout devel
./patch-nanomsg.sh $BASEDIR/nanomsg
# Build and install nanomsg in the local folder
cd ../nanomsg
./configure --prefix=$BASEDIR/local
make -j8 && make install
# Build the nanomsg tests
cd ../nanomsg-transport-ofi/test
make nanomsg NANOMSG_DIR=$BASEDIR/local
```
Then, start one server and one client:
```shell
# Start a server (the IP address should be a local usnic address)
./test_nanomsg_timing node0 ofi://192.168.0.1:5050
# Start a client (in another machine)
./test_nanomsg_timing node1 ofi://192.168.0.1:5050
```
You can confirm the `usnic` is selected when you see the following:
```
OFI[H]: Using fabric=usnic_0, provider=usnic
```
The server should crash a segfault while the client will keep trying to send messages. Interrupt it with CTRL+C.

**Comment by goodell** [comment] 2016-03-04 14:26
@bturrubiates can you take a look?

**Comment by bturrubiates** [comment] 2016-03-04 16:25
Yeah, sure. 



> The server should crash a segfault while the client will keep trying to send messages. Interrupt it with CTRL+C.

I'm not seeing that behavior, I don't think I'm even getting far enough. It seems server side I'm getting stuck before I can really see the problem: 

```
[-01426548480] OFI[B]: Creating bound OFI socket (domain=10.5.20.195, service=5050)
OFI[H]: Using fabric=usnic_0, provider=usnic
[-01426548480] OFI[B]: nn_bofi_handler state=1, src=-2, type=-2
TIM: I will be receiving
-- Receiving 0
[-01420097792] OFI[B]: bofi_accept_thread: Waiting for incoming connections
[-01420097792] OFI[B]: bofi_accept_thread: Accepted connection, exiting
[-01424439552] OFI[B]: nn_bofi_handler state=2, src=4001, type=1
[-01424439552] OFI[B]: Allocating new SOFI
[-01424439552] OFI[i]: Initializing Input FSM
[-01424439552] OFI[i]: Allocating buffers len=2, size=131072
[-01424439552] OFI[i]: Allocated RxMR chunk=0x2aaaac0010b0, key=61953
[-01424439552] OFI[i]: Allocated RxMR chunk=0x2aaaac0010f0, key=61954
[-01424439552] OFI[o]: Initializing Output FSM
[-01424439552] OFI[-]: Initializing MRM with len=2, key=62209
[-01424439552] OFI[-]: Allocated MRM chunk=0x2aaaac5387d0
[-01424439552] OFI[-]: Allocated MRM chunk=0x2aaaac5388b0
[-01424439552] OFI[S]: Starting FSM
[-01424439552] OFI[S]: nn_sofi_handler state=1001, src=-2, type=-2
[-01424439552] OFI[S]: Performing handshake
[-01424439552] OFI[S]: Posting buffers for receiving handshake
[-01424439552] OFI[i]: Blocking RX Post max_sz=4
[-01424439552] OFI[i] ### POSTING RECEIVE BUFFER len=1024, ctx=0x2aaaac537fd0
[-01424439552] OFI[S]: Error preparing for handshake receive (error=0)
[-01424439552] OFI[S]: Receiving handshake
[-01424439552] OFI[i]: Blocking RX Recv max_sz=4, timeout=1000
[-01424439552] OFI[i]: Success (Success)
[-01424439552] OFI[S]: Error receiving handshake (error=-5)
[-01424439552] OFI[S]: nn_sofi_handler state=1001, src=1106, type=1
[-01424439552] OFI[S]: Stopping FSM
[-01424439552] OFI[S]: Stopping []
[-01424439552] OFI[S]: Stopping core
[-01424439552] OFI[S]: We are now closing
[-01424439552] OFI[S]: Waiting for all components to be idle
[-01424439552] OFI[S]: Stopping OFI endpoint
[-01424439552] OFI[S]: Stopping pipebase
[-01424439552] OFI[B]: nn_bofi_handler state=2, src=4000, type=1210
[-01424439552] OFI[B]: Marking SOFI as inactive
[-01424439552] OFI[S]: Cleaning-up SOFI
[-01424439552] OFI[i]: Terminating Input FSM
Assertion failed: self->next == NN_QUEUE_NOTINQUEUE (src/utils/queue.c:102)
```

**Comment by bturrubiates** [comment] 2016-03-04 16:26
> What I can't understand is the fact that the context from the first fi_recv remains the same even after the second call to fi_recv! And of course this causes a segfault because the context pointer is invalid.

I think this should have been fixed in #1809.

**Comment by wavesoft** [comment] 2016-03-04 19:57
Thanks @bturrubiates for having a look. From your logs it seems that the handshake rx operation raised an error CQ event with code FI_EIO (-5). I saw this before, what could it be?
```
[-01424439552] OFI[S]: Error receiving handshake (error=-5)
```
FYI: right after the connection is established I perform a synchronous (blocking) Rx/Tx operation between the two nodes in order to exchange some handshake information. For reference, the handshake functions [are here](https://github.com/wavesoft/nanomsg-transport-ofi/blob/devel/src/transports/ofi/sofi.c#L81), and they are calling the [nn_sofi_out_tx](https://github.com/wavesoft/nanomsg-transport-ofi/blob/devel/src/transports/ofi/sofi_out.c#L371) function to send data and [nn_sofi_in_rx_post](https://github.com/wavesoft/nanomsg-transport-ofi/blob/devel/src/transports/ofi/sofi_in.c#L544) / [nn_sofi_in_rx_recv](https://github.com/wavesoft/nanomsg-transport-ofi/blob/devel/src/transports/ofi/sofi_in.c#L571) functions to receive data.

> I think this should have been fixed in #1809.

I will give a spin to the master branch and let you know...

**Comment by wavesoft** [comment] 2016-03-04 19:59
Nope, sorry, my mistake. The error originates from [here](https://github.com/wavesoft/nanomsg-transport-ofi/blob/devel/src/transports/ofi/sofi.c#L118), which means that the received data size do not match the expected size:

```c
    /* Validate size of received data */
    if (sz != sizeof(self->hs_remote)) return -EIO;
```

**Comment by bturrubiates** [comment] 2016-03-04 20:02
> I will give a spin to the master branch and let you know...

Thanks

> Nope, sorry, my mistake. The error originates from here, which means that the received data size do not match the expected size:

I wonder why that would differ between our setups...

**Comment by wavesoft** [comment] 2016-03-04 20:19
> I wonder why that would differ between our setups...

Ok, I see the same behaviour with you when using the master branch. 

I also checked the problem and what I see is that the [`fi_cq_sread`](https://github.com/wavesoft/nanomsg-transport-ofi/blob/devel/src/transports/ofi/sofi_out.c#L397) function on the rx operation returns -95, and then the [`fi_cq_readerr`](https://github.com/wavesoft/nanomsg-transport-ofi/blob/devel/src/transports/ofi/sofi_out.c#L406) reads the error code 0. That's why you see this  suspicious message before eventually failing:
```
[-01424439552] OFI[i]: Success (Success)
```

**Comment by bturrubiates** [comment] 2016-03-04 20:27
> I also checked the problem and what I see is that the fi_cq_sread function on the rx operation returns -95, and then the fi_cq_readerr reads the error code 0. That's why you see this suspicious message before eventually failing:

I'm bisecting to find the change that caused this.

**Comment by bturrubiates** [comment] 2016-03-04 20:37
So this behavior seems to be caused by #1639. Does this use `FI_WAIT_NONE` with `sread`?

**Comment by wavesoft** [comment] 2016-03-04 20:43
Indeed, [you are right](https://github.com/wavesoft/nanomsg-transport-ofi/blob/devel/src/transports/ofi/hlapi.c#L850), thanks for this! It was a leftover from the previous version of my code were I was not using blocking CQ operations.

And the master branch seems to have fixed my issue, so I guess you can close this issue.

**Comment by bturrubiates** [comment] 2016-03-04 20:46
> And the master branch seems to have fixed my issue, so I guess you can close this issue.

Awesome :+1:

**Closed by bturrubiates** 2016-03-04 20:46 UTC
