### ISSUE TITLE
check for FI_COLLECTIVE enabled caused multi node all_reduce_perf test to hang indefinitely for tcp provider

### ISSUE THREAD

**Issue by oleksandr-zubenko** [ofiwg/libfabric#6441] opened 2020-11-30 19:09 UTC
PR #6416 caused multi node all_reduce_perf test to hang indefinitely for tcp provider

Test conducted on 3 nodes and if any of nodes has this bitwise AND (info->caps & FI_COLLECTIVE) enabled instead of bitwise OR, the test starts and hangs.

Commit which caused hang: https://github.com/ofiwg/libfabric/commit/0164756e4148bba9a05ce3d6f7a939db726720ec

CI run example, where test initiated and terminated by 30 minute timeout: https://libfabric-ci.aws.a2z.com/job/nccl-multi-node/PROVIDER=tcp%3Bofi_rxm,label=alinux/1477/console

Issue reproducible locally.

Components:  
EFA installer: https://efa-installer.amazonaws.com/aws-efa-installer-latest.tar.gz
Libfabric: https://github.com/ofiwg/libfabric -b 'master'
NCCL: https://github.com/NVIDIA/nccl.git (NCCL_2_7_8='033d799524fb97629af5ac2f609de367472b2696')
aws-ofi-nccl: https://github.com/aws/aws-ofi-nccl.git -b master
nccl-tests: https://github.com/NVIDIA/nccl-tests.git -b master

**Comment by shefty** [comment] 2020-11-30 23:56
PR #6421 attempts to address the issue. There were several issues that have been uncovered as a result of this change.  However, PR 6421 is still seeing CI failures, the cause of which is unknown (it could be outside of libfabric).

PR #6440 is a work-around which disables some of the rxm optimization features and instead forces the use of bounce buffers.  That PR has already been merged and should avoid the hangs.  However, the underlying issues will still be present until 6421 can be merged.

**Comment by shefty** [comment] 2020-12-02 23:20
This should be fixed in master, or at least the offending code disabled.

**Closed by shefty** 2020-12-02 23:20 UTC
