### ISSUE TITLE
Unable to disable gdrapi linkage/gdrcopy

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#6602] opened 2021-02-26 18:19 UTC
We've been trying to disable linkage of gdrapi, however we run into the following build issues:
We've tried both --with-gdrcopy=no and --without-gdrcopy and both result in the following:

> ./libtool: line 5986: cd: no/lib64: No such file or directory
> libtool: link: cannot determine absolute directory name of `no/lib64'
> make[1]: *** [libpsmx2.la] Error 1
> make[1]: Leaving directory
> `/work/06753/soychan/frontera/BUILDS/20210226/daos/build/external/release/ofi'
> make: *** [all] Error 2
> BuildFailure: ofi failed to build:

It appears that in both cases 'no' is being passed as a literal value instead of being interpreted as 'disable' flag.

OFI: 12.0.1rc1

**Comment by rajachan** [comment] 2021-03-02 20:23
The package check for gdrcopy is done unconditionally:
https://github.com/ofiwg/libfabric/blob/ef047202101d44a3c41dcdb2ff2ef96724df1cb4/configure.ac#L605

The configure code is missing a test for the --with-gdrcopy flag `AS_IF([test x"$with_gdrcopy" != x"no"],....)`. While we are in here, we should also make it conditional on `have_libcuda`, since gdrcopy by itself will not be of much use.

**Comment by shefty** [comment] 2021-03-02 21:55
@wzamazon - according to git blame, you added this check.  Is there any chance of updating it within the next day, so it can get picked up for 1.12.0rc3?

From an email discussion, the issue is that the app is compiled on a system with this present, but run on systems where the libraries are not available.

**Comment by wzamazon** [comment] 2021-03-03 18:49
@shefty  I will be working on it today.

**Comment by wzamazon** [comment] 2021-03-03 21:57
Opened PR https://github.com/ofiwg/libfabric/pull/6607

**Comment by wzamazon** [comment] 2021-03-04 18:57
@frostedcmos The PR has been merged. I tested all the combinations I can think of and the test results were in the PR too. Please let me know if the last master branch fix the issue for you.

**Closed** 2021-03-06 02:26 UTC
Labels: bug
