### ISSUE TITLE
Incorrect cq_flags reported by verbs provider

### ISSUE THREAD

**Issue by johannlombardi** [ofiwg/libfabric#7359] opened 2022-01-10 19:57 UTC
With the patch to track "transmit operation through to completion" (https://github.com/ofiwg/libfabric/commit/12c3e17f3b207e51dc6c33bfd9a66b74775c889c#diff-a419c87dee306c7263a10e3ad0503821029404078cedb9c0bad8e8c0ed6d8755), we see completions on FI_RMA operations with incorrect cq_flags.

From the mercury logs:

`na_ofi_cq_process_event(): na_ofi_op_id=0x7f279433fa90, flags=0x4, cq_flags=0x402
`

Mercury issued a FI_RMA operation and got back FI_MSG | FI_RECV in the cq_flags. We have also seen occurrences where we got back FI_MSG | FI_SEND. Reverting the PR removes those errors.

We suspect that it might be due to the following changes in the case of FI_RMA operations:
https://github.com/ofiwg/libfabric/blob/main/prov/verbs/src/verbs_cq.c#L255
https://github.com/ofiwg/libfabric/blob/main/prov/verbs/src/verbs_cq.c#L69

**Comment by shefty** [comment] 2022-01-10 20:01
Are you using the verbs provider directly or through rxm?

**Comment by shefty** [comment] 2022-01-10 20:04
And based on the links you gave, these are for failed RMA operations, correct?  (Btw, verbs doesn't provide anything other than the wr_id in the case of failure.  Everything else needs to be discovered based on that.)

**Comment by johannlombardi** [comment] 2022-01-10 20:18
We are using verbs+rxm. We are speculating that it might happens on failed RMA operations, but we have no proof yet.

The other thing that confuses me is how wc->opcode can be used as a bit flag (wc->opcode |= IBV_WC_RECV) and in a switch statement at the same time.

**Comment by shefty** [comment] 2022-01-10 20:29
From verbs.h:
```
enum ibv_wc_opcode {
	IBV_WC_SEND,
	IBV_WC_RDMA_WRITE,
	IBV_WC_RDMA_READ,
	IBV_WC_COMP_SWAP,
	IBV_WC_FETCH_ADD,
	IBV_WC_BIND_MW,
	IBV_WC_LOCAL_INV,
	IBV_WC_TSO,
/*
 * Set value of IBV_WC_RECV so consumers can test if a completion is a
 * receive by testing (opcode & IBV_WC_RECV).
 */
	IBV_WC_RECV			= 1 << 7,
	IBV_WC_RECV_RDMA_WITH_IMM,
```
It's designed for this sort of use.

**Comment by johannlombardi** [comment] 2022-01-10 20:34
Yeah, but if you set "| IBV_WC_RECV" on a opcode that isn't already equal to IBV_WC_RECV, then vrb_cq_read_msg_entry() will always hit the "default:" case in the switch statement. Is that intended?

**Comment by shefty** [comment] 2022-01-10 20:43
That is set within this check:
```
if (ctx->op_ctx == VRB_POST_SQ)
	wc->opcode &= ~IBV_WC_RECV;
else
	wc->opcode |= IBV_WC_RECV;
```
The else condition corresponds to operations posted to the receive queue (VRB_POST_RQ or VRB_POST_SRQ)

**Comment by shefty** [comment] 2022-01-10 23:37
I haven't been able to determine how the commit referenced above is causing the issue.  I think it just happens to be exposing some other issue dealing with error completions.

This code path is taken in both the success and error cases, and is responsible for setting the CQ flags:
https://github.com/ofiwg/libfabric/blob/main/prov/verbs/src/verbs_cq.c#L47

The problem is that the wc->opcode is undefined in the case of error.  In vrb_poll_cq:
https://github.com/ofiwg/libfabric/blob/main/prov/verbs/src/verbs_cq.c#L251

we toggle whether the completion was for a send or receive.  That information is needed for other tracking purposes.  However, IBV_WC_RECV should end up being the only bit of the opcode that's set correctly.  AFAICT, all other bits are invalid.

Based on what I can tell from reading the code, the CQ flags for an error completion could map to any operation, or be unset.  BUT, since the code actually tracks for operations posted to the SQ or RQ, the IBV_WC_RECV bit itself should be correct.  So, I'm puzzled how an RMA send generated the FI_RECV | FI_MSG flags.  Incorrect flags make sense -- just not that specific mismatch.

**Comment by bfaccini** [comment] 2022-01-11 11:41
We have also encountered some cases where we trigger this assert in rpm_handle_comp() : 
```
         case RXM_RMA:
                 tx_buf = comp->op_context;
                 assert((comp->flags & (FI_WRITE | FI_RMA)) ||
                        (comp->flags & (FI_READ | FI_RMA)));`
```
and again because the flags are unexpectedly set to "FI_MSG | FI_RECV".

**Comment by shefty** [comment] 2022-01-11 15:41
I'm working on a patch to fix the flags, particularly in the error case.  But it's still not clear to me what path is setting FI_RECV.

**Comment by shefty** [comment] 2022-01-12 22:44
See if PR #7365 helps this any.

**Comment by bfaccini** [comment] 2022-01-14 16:18
Hello @shefty , [PR-7365](https://github.com/ofiwg/libfabric/pull/7365) did not help.

On the other hand we have continued to investigate this issue on our side, and we have been able to determine that the completions causing the assert() in rpm_handle_comp() have an opcode of 0x88/136/IBV_WC_DRIVER2, a len of 0, and a status of 0 ...IBV_WC_DRIVER2
It appears that this particular libibverbs usage of IBV_WC_DRIVER2 opcode has been introduced by the following libibverbs commit : 
```
commit 8ff1c5c3c4117fe0cd36b451be9b9729becc9eb5
Author: Mark Zhang <markzhang@nvidia.com>
Date:   Thu May 13 12:26:43 2021 +0300

    mlx5: Introduce mlx5dv_wr_raw_wqe builder
    
    Introduce mlx5dv_wr_raw_wqe builder to be used for building a raw work
    request. The user needs to set all segments and fields (except the
    ctrl.wqe_index and ctrl.signature, which will be overridden by driver)
    that follows PRM definition.
```
and is definitely a pure MLNX thing, which appears to need a specific handling in libfabric's verbs provider, particularly starting in vrb_cq_read_msg_entry() where the current code allows such completions to be treated in case's default where just nothing is being done/changed presently.

BTW, it is interesting that folks at SPDK have encountered the same problem, as its is reported in their report issue [#2310](https://gitmemory.cn/repo/spdk/spdk/issues/2310).

**Comment by shefty** [comment] 2022-01-14 18:25
Looking at the link and description, this looks like they broke verbs.  This somewhat explains to me how the FI_RECV flag was getting set.  #7365 should still be needed to properly handle error completions.  In that patch, I only used the saved work request value in the error case.  I can look at using the saved value in the success path as well, which may work around the verbs bug.

What version of libibverbs or MOFED are you using?  Is this in a release version?

**Comment by johannlombardi** [comment] 2022-01-14 19:48
Any MOFED version > 5.4-1.0.3.0 suffers from the issue. On our testbed, we are using MLNX_OFED_LINUX-5.5-1.0.3.2.
Yes, we only use official release.

**Comment by shefty** [comment] 2022-01-15 00:33
I updated PR #7365 to use the saved send opcode to set the work completion opcode.  The WC opcode set by verbs should be ignored now in all cases.

**Comment by johannlombardi** [comment] 2022-01-17 12:07
Thanks @shefty for the updated PR. Early results are encouraging. We are going to run more tests.

**Comment by johannlombardi** [comment] 2022-01-18 10:22
Testing looks good. @shefty, could you please advise whether you think that it is safe for us to integrate this patch into our next bug fix release?

**Comment by shefty** [comment] 2022-01-18 17:22
Yes, I think that patch is safe.  I want to update the commit message to capture the problem reported here in more detail, but the code changes will remain as-is.

**Comment by shefty** [comment] 2022-01-19 00:38
Fixed merged into main

**Closed by shefty** 2022-01-19 00:38 UTC

**Comment by shefty** [comment] 2022-01-21 00:10
If DAOS uses RMA writes with CQ data, you will want to pick up the following commit as well:

https://github.com/ofiwg/libfabric/pull/7391/commits/790b7b816488074ac8e15b46ff95f7262432bf2a
