### ISSUE TITLE
fi_cntr_read/wait will not progress receive queue with socket provider

### ISSUE THREAD

**Issue by KaimingOuyang** [ofiwg/libfabric#6250] opened 2020-09-15 00:11 UTC
We call fi_readmsg for RMA operations and record the number of issued operations as issued_cnt. On the other hand, we bind rma counter (done_cnt) with attributes FI_READ | FI_WRITE to track the number of completed rma operations.

We need to call fi_cntr_read/wait in a loop until done_cnt is equal to issued_cnt. However, we found, with socket provider, ofi will not progress receive queue when calling fi_cntr_read/wait. Since we only call fi_cntr_read/wait to make a process, when two processes call fi_readmsg to each other, the done_cnt will never increase and we will get stuck.

We are wondering whether it is possible to add a receive queue progress for fi_cntr_read/fi_cntr_wait in socket provider? Thanks.

**Comment by shefty** [comment] 2020-09-15 00:23
The socket provider supports auto progress.  We're moving away from supporting the socket provider.  Can you test with the tcp provider?

**Comment by hzhou** [comment] 2020-09-15 01:26
> 
> 
> The socket provider supports auto progress. We're moving away from supporting the socket provider. Can you test with the tcp provider?

@shefty Did you mean that sockets provider *doesn't* support auto progress? Implying that it need support auto progress and enable auto progress in order for a pure `fi_cntr_read/wait` loop to work?

**Comment by hzhou** [comment] 2020-09-15 02:34
Looking into the issue, apparently when we bind a simple endpoint to a `cntr`, it is only bound to the `tx_ctx` of the `cntr`. Thus when it calls `sock_cntr_progress`, it only progresses the `tx_ctx`, which of course is insufficient. How do we bind the endpoint to **both** the `tx_ctx` and `rx_ctx` of the `cntr`?

**Comment by hzhou** [comment] 2020-09-15 03:15
Further reading the code: FI_READ | FI_WRITE only binds the tx_ctx. FI_REMOTE_READ | FI_REMOTE_WRITE will bind the rx_ctx, but we don't really want to track FI_REMOTE_READ and FI_REMOTE_WRITE, what should we do?

Is it possible to bind the `rx_ctx` to `cntr` but without tracking `FI_REMOTE_READ | FI_REMOTE_WRITE` events in the counter?

**Comment by hzhou** [comment] 2020-09-15 03:23
It'll be so much easier if there is `fi_progress_rx` and `fi_progress_tx` api.

**Comment by shefty** [comment] 2020-09-15 16:33
The sockets provider supports auto-progress.  You could enabled that and avoid progressing on cntr/cq reads completely.  Auto-progress will result in spawning a thread to drive progress, however.

To progress receives, you can read the CQ associated with the endpoint that was bound for FI_RECV.  You wouldn't need a counter.  Your progress loop would check the tx cntr, but also call cq_read.

Sockets was written in part to check for application correctness.  So I think it's behavior is expected.

The socket provider is extremely complex .  We're focusing development on RxM and TCP providers.  Are you able to run with those providers instead?  If not, can you report what problems you see there?  Note that you may run into the same issue because of how you're handling progress.

There are options for making more generic progress.  See:

https://ofiwg.github.io/libfabric/master/man/fi_poll.3.html

A poll set allows you to add multiple counters and CQs to it.  Once added, an application only needs to call fi_poll() to drive progress across all of them.  libfabric does not have a generic fi_progress() call to drive progress across everything because of the performance impact such a call would have.  For example, some progress checks require dropping into the kernel to read events, such as connections requests.  Doing that on every progress call would significantly impact data transfer performance.  However, fi_poll() can be configured to provide equivalent behavior.

**Comment by hzhou** [comment] 2020-09-15 17:56
> 
> To progress receives, you can read the CQ associated with the endpoint that was bound for FI_RECV. You wouldn't need a counter. Your progress loop would check the tx cntr, but also call cq_read.

Our current code does that. However, reading the CQ means we also need process the CQ entries or enqueuing it, which is undesirable for the part of code we are concerning. 

> 
> Sockets was written in part to check for application correctness. So I think it's behavior is expected.

We are using `sockets` for the correctness reason. Thus if a construct, e.g. only `fi_cntr_read/wait` on `tx_ctx` doesn't work for `sockets`, we are worried that may be incorrect code for providers in general. 

I guess we are looking for some "official" statement from libfabric, that is it "correct" to only use `fi_cntr_read/wait` in a loop and expect progress in general? In another word, is the behavior of `sockets` incorrect?

Personally, since for `sockets` at least, it needs progress from both `rx_ctx` and `tx_ctx` to actually progress, I think only attaching and progress `tx_ctx` in `sock_cntr_progress`, under `FI_PROGRESS_MANUAL`, is incorrect.

> 
> The socket provider is extremely complex . We're focusing development on RxM and TCP providers. Are you able to run with those providers instead? If not, can you report what problems you see there? Note that you may run into the same issue because of how you're handling progress.

There are issues and priorities. We'll follow up separately.

> 
> There are options for making more generic progress. See:
> 
> https://ofiwg.github.io/libfabric/master/man/fi_poll.3.html
> 
> A poll set allows you to add multiple counters and CQs to it. Once added, an application only needs to call fi_poll() to drive progress across all of them. libfabric does not have a generic fi_progress() call to drive progress across everything because of the performance impact such a call would have. For example, some progress checks require dropping into the kernel to read events, such as connections requests. Doing that on every progress call would significantly impact data transfer performance. However, fi_poll() can be configured to provide equivalent behavior.

Interesting. How's the performance? For example, if a single `tx_ctx` are attached to multiple counters and CQs in the poll set, does it get progressed multiple times in each poll?

**Comment by minsii** [comment] 2020-09-15 18:40
@shefty Going back to the posted problem itself, I want to clarify the use case of `fi_cntr_read/wait` in our case (MPICH/ofi), so you might have more information about our demands. 

We use `cntr` to track completion of locally issued MPI RMA operations which use `fi_{read,write}msg` internally. When waiting for the completion of outstanding RMA operations in MPICH, we want to **make only necessary progress to minimize the progression overhead**. To be specific, if MPICH knows that we need progress only for RMA now, we want to only trigger the necessary OFI progress for `fi_{read,write}msg` and `cntr` updates.

We assume that doing a `fi_cntr_read`-loop would be sufficient for the above case, as `fi_cntr_read` internally should make the necessary progress for reading and updating `cntr`, no matter the domain `{control|date}_progress` is `FI_PROGRESS_AUTO` or not. In other words, when the user is using only cntr-based routines, the provider should not assume that the user will manually make calls to `fi_cq_read`. Can you please confirm is this assumption correct?

(Reason why we set `FI_PROGRESS_MANUAL` in MPICH)
- First, we want to avoid an additional progress thread because it adds CPU contention overhead. MPI does not require complete asynchronous progression (i.e., user has to make MPI calls to ensure progress), thus such an overhead is unnecessary for MPI.
- Second, we can control the necessary progression in MPICH in a fine-grained manner. For example, if we know only `fi_{read,write}msg` is called, we will make progress only for cntr-updates but skip progression for CQ.

**Comment by shefty** [comment] 2020-09-15 19:07
The official response is that general progress is never guaranteed; however, the provider is required to take action necessary to complete the operation locally.  Hopefully this example clarifies what is meant.

1.  If completing a send requires checking the receive queue for an ack, then the provider owns that responsibility.  The application only needs to progress the send CQ.  Note the provider only needs to check for an ack when one is expected (the send has progressed to that point).

2.  If completing a send requires that the peer handle the receive, the peer application owns that responsibility.  That is, progressing a send CQ is not responsible for progressing inbound transfers.

3.  If the peer application does not attempt to progress inbound transfers, deadlock is possible.

The problem is related to your comment, but also deeper.  For example, if the provider must progress everywhere, then it may need to queue receive completions somewhere.  Additionally, this can impact buffering.  It may not be enough to read receive completions and store them.  Additional receive buffers may need to be posted for progress to continue.  For the provider to make progress on its own, it would need to post those buffers.  That could result in all data transfers having to go through bounce buffers.  There may be other implications here.

In the case of tcp sockets, RMA writes can be completed at the sender as soon as the data is queued on the socket, depending on the desired completion semantics.  TCP flow control will dictate when that data is actually transferred to the peer.  For progress to be made, the peer must read data off the socket, which requires progressing the recv CQ.  See this note under progress in the fi_domain man page:

```
Manual progress requirements not only apply to endpoints that initiate transmit operations, but also to endpoints that may be the target of such operations. This holds true even if the target endpoint will not generate completion events for the operations. For example, an endpoint that acts purely as the target of RMA or atomic operations that uses manual progress may still need application assistance to process received operations.
```

**Comment by shefty** [comment] 2020-09-15 19:16
I'm using CQ read as a generic option.  Reading from a counter is equivalent, but has the same problem.  If completing the operation locally requires that the peer process incoming messages, and the peer does not do this, then stalls are possible.

I'm trying to be clear on the reason for the deadlock.  It's not that posting an RMA write requires checking the local receive queue.  It's that it requires the peer to check the receive queue for the RMA write to progress.

A provider which can drive RMA progress automatically (such as verbs) would not have this limitation.

**Comment by hzhou** [comment] 2020-09-15 19:51
@shefty Thanks for the in-depth answer. But I have to say I am not sure what is the get-away message. Should we assume that, for correct providers, `fi_cntr_read` alone does ensure progress -- assuming whatever peer progress is happening (focusing on the code locally necessary)? If that is the case, we'll code for this case and try to fix `sockets` if necessary. Otherwise, we may have to either "poll" additional counters or CQs, which potentially will have performance impact.

**Comment by shefty** [comment] 2020-09-15 20:18
fi_cntr_read is sufficient to drive the progress of operations that the process *initiates*.  However, that will not avoid deadlock.  To avoid deadlock, the local process *may* need to ensure that operations initiated from its peers can also complete.

Imagine 2 processes trying to send 1 GB of data to each other over tcp sockets.  If both sit in a tight loop retrying a send call until all data has been transferred, the send and receive buffers on both sides will fill up, and the application will deadlock.  The processes must call recv to clear buffer space.  The recv call is not related to the local send operation, but the peer's.  That is, if one process used a send loop, while the peer used a recv loop, the operation works.  The deadlock is a condition resulting from the application's use of the socket, and not the socket behavior itself.

I do not know if sockets has a real problem in this area.  From the discussion so far, it sounds like the deadlock problem is in MPI.

You need correctness before performance impact has significant meaning.

**Comment by hzhou** [comment] 2020-09-15 21:48
@shefty I think I am getting it. It probably is due to missing remote progress on recv context.

**Comment by minsii** [comment] 2020-09-15 22:36
@shefty Thanks for the clarification. I think the semantics rules are clear to us and we did more debugging to confirm that it is because we did not progress receive queue on the peer process (e.g., the peer is also waiting in a loop of `fi_cntr_read`).

> - If completing a send requires checking the receive queue for an ack, then the provider owns that responsibility. The application only needs to progress the send CQ. Note the provider only needs to check for an ack when one is expected (the send has progressed to that point).
> - If completing a send requires that the peer handle the receive, the peer application owns that responsibility. That is, progressing a send CQ is not responsible for progressing inbound transfers.
> - If the peer application does not attempt to progress inbound transfers, deadlock is possible.

We understand that we need manually make receive queue progress in MPICH for RMA with the sockets provider (e.g., by calling `fi_cq_read`). But such thing causes unnecessary overhead for providers such as verbs and psm2, in which we concern about the performance. So we want to avoid the manual-receive-queue-progression for those providers. I don't find a way for MPICH to query OFI whether the provider has the capacity to drive RMA progress automatically. Does libfabric provide such a query functionality?

**Comment by shefty** [comment] 2020-09-15 23:09
There's an fi_domain_attr::data_progress field that may be useful.  This is a generic value that applies to all transfers, though, and is not RMA specific.

For verbs, I believe the default is FI_PROGRESS_AUTO.  Tcp reports FI_PROGRESS_MANUAL.  Sockets reports AUTO by default, but can be forced into manual through fi_getinfo.

Please be aware that verbs emulates tag matching.  If RMA is mixed with tag matching, or the application has some serialization between the two, then deadlock might still be possible.  (I'm not sure).  I would recommend having a environment variable that can be enabled for force receive side progress as a backup.

**Comment by minsii** [comment] 2020-09-16 17:14
Thanks, @shefty . I do see the `fi_domain_attr.data_progress` field. But we are looking for a more fine-grained information for us to make the most efficient decision in MPICH. For instance, we don't want to enable a progress thread that makes progress for everything. We want to trigger minimal & necessary progress only for RMA if we know only RMA has been issued. or we want to do progress only for tag matching send/recv but skip RMA progress if we see only send/recv has been issued.

I guess that this level of information is not exposed from libfabric yet. Is there any plan to support this feature? 

As an example to utilize such fine-grained information, we got advantage from the `fi_{fetch_|compare_}atomicvalid` APIs when deciding how we can implement MPI atomics in MPICH.

**Comment by shefty** [comment] 2020-09-16 18:17
That level of information is not exposed, and there's no current plans to expose it.  By far, the general feedback on the API is that it needs to be simpler, not more complex to use.  Auto vs manual progress isn't limited to just the operation being submitted, but also the completion model being specified.  E.g. RMA with TRANSMIT_COMPLETE semantics can be auto, where RMA with COMMIT_COMPLETE semantics may not be.

Again, the problem you are facing isn't that the local process is only posting RMA operations, it's what the peer processes are doing.  If you limit progress to only outbound transfers, inbound transfers are not being processed, which stalls the peers.  The optimization you're wanting will disable processing of all inbound traffic.  Is that really desirable?

**Comment by minsii** [comment] 2020-09-16 18:42
> Again, the problem you are facing isn't that the local process is only posting RMA operations, it's what the peer processes are doing. If you limit progress to only outbound transfers, inbound transfers are not being processed, which stalls the peers. The optimization you're wanting will disable processing of all inbound traffic. Is that really desirable?

Not really. We enable the progression also for inbound traffic on the peer process if we know **RMA is going to be used and manual inbound traffic progression is required**. For instance, we can get such global information at MPI window creation time so that both local and peer processes can enable or disable the necessary progression.

We want to find a way to avoid inefficient progression. To be specific, today we simply assume that inbound traffic progression might be needed, and thus always trigger OFI full progression (e.g., by calling `fi_cq_read`). This causes expensive (and unnecessary) overhead if the provider can automatically progress all outstanding operations. To get rid of such situation, we need several information:
1. Which operations are being issued on all processes (not only on the local process)? <- we already get this information in MPI
2. Does the operation require send-side or receive-side progression in software and whether the OFI application (i.e., MPI here) has the responsibility to trigger it? <- we need this information from OFI, which is missing in current API.

To get 2, I don't think it will make the OFI interface more complex. We essentially just need a query function similar to that for atomics. I.e., I can query the provider whether the RMA (or tag-matching send/recv) with specific semantics and even with specific parameters (e.g., maxsize) require any kind of manual progression. The query API will likely be triggered at init time, so no performance concern and it does not impact on any data transfer calls.

**Closed** 2020-09-30 23:02 UTC
