### ISSUE TITLE
Clarify behavior of wait objects

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1645] opened 2016-01-22 19:09 UTC
This is related to discussion that happened in #1533. The semantics of wait objects are not clear to me and the `fi_dgram_waitset` test and the comments in #1533 seem to suggest different behaviors.

@shefty Could you comment on the information in [this](https://github.com/ofiwg/libfabric/files/101293/wait_objects.pdf) slideshow. I'd like to clarify which functions should reset the wait object, which use cases are valid, and determine if there is a risk for races. Once this is decided I can update the appropriate man pages.

**Comment by shefty** [comment] 2016-01-22 19:49
I have this problem in my inbox to address when I get time.  I just haven't had time yet.

slide 6 - I will strongly object to fi_cq_read needing to reset the wait object.  That will have too large of an impact on performance.  Not only may it force the caller to drop into the kernel on every CQ read call, but it can result in more interrupts being generated than are necessary.

Wait objects are not clearly defined as edge triggering or level triggered.  They should be edge triggered.  IOW, only new completions will signal the wait object.

**Comment by shefty** [comment] 2016-01-22 22:00
I spent some more time reading through the slides.  I think we need to make it clear that once a wait object has been signaled, it will not be reset until the corresponding CQ has been drained.  That is indicated by fi_cq_sread() returning -FI_EAGAIN.

I want to avoid an explicit rearm call.  Verbs has that, and it has been an endless source of programmer errors.  We want to push this responsibility down.  There's a race between clearing the CQ, rearming for events, and receiving another completion in between, which requires clearing the CQ a second time.

I'm not sure what the desired behavior in the slide examples is supposed to be. For example, in the poll case, is the intent to loop until either an error occurs or a completion is read?  Is there an assumption that a CQ with a wait object starts as armed?  (That seems like a valid assumption.)

**Comment by shefty** [comment] 2016-01-22 22:16
Assuming that the examples are intended to handle a generic case and not the first completion, any wait call should be inside of some sort of loop.  This is needed to handle the race condition of read-rearm-read, where the second read pulls a completion off the CQ that actually occurred after the rearm was done.  This leaves the CQ signaled, but without any completion.  (And the second read is necessary to pick up a completion that arrives before the rearm.)  So, I think it needs to be structured as this:

````
do {
    ret = poll(&pfd, 1, -1);
    while (ret > 0) {
        ret = fi_cq_sread(..., 0);
        if (ret > 0)
            handle_completion(...);
    }
} while (ret == -FI_EAGAIN);
/* unexpected error */
````

**Comment by bturrubiates** [comment] 2016-01-25 20:00
> slide 6 - I will strongly object to fi_cq_read needing to reset the wait object. That will have too large of an impact on performance. Not only may it force the caller to drop into the kernel on every CQ read call, but it can result in more interrupts being generated than are necessary.

So what's the intended behavior if an app waits on a wait object using `fi_wait` or `poll` and drains the completion queue using `fi_cq_read`? I can see how wait objects being edge-triggered would solve this issue, but if we assume level-triggered then mixing synchronous/asynchronous reads can lead to an inconsistent state.

> Wait objects are not clearly defined as edge triggering or level triggered. They should be edge triggered. IOW, only new completions will signal the wait object.

> I spent some more time reading through the slides. I think we need to make it clear that once a wait object has been signaled, it will not be reset until the corresponding CQ has been drained. That is indicated by fi_cq_sread() returning -FI_EAGAIN.

If the wait objects are edge-triggered then why would they need to be reset at all? Doesn't edge-triggered imply that the active state doesn't signifiy "signaled" anymore?

> I want to avoid an explicit rearm call. Verbs has that, and it has been an endless source of programmer errors. We want to push this responsibility down. There's a race between clearing the CQ, rearming for events, and receiving another completion in between, which requires clearing the CQ a second time.
> 
> I'm not sure what the desired behavior in the slide examples is supposed to be. For example, in the poll case, is the intent to loop until either an error occurs or a completion is read? Is there an assumption that a CQ with a wait object starts as armed? (That seems like a valid assumption.)

Yeah, that was my intent in the example. IMO if a CQ has been opened with a wait object, then it should be armed by default.

**Comment by shefty** [comment] 2016-01-25 22:55
> So what's the intended behavior if an app waits on a wait object using
> fi_wait or poll and drains the completion queue using fi_cq_read? I can
> see how wait objects being edge-triggered would solve this issue, but if
> we assume level-triggered then mixing synchronous/asynchronous reads can
> lead to an inconsistent state.

Apps that really want to wait should be directed to use fi_cq_sread() for all operations.  Fi_cq_sread() should be equivalent to fi_cq_read() -- minus a couple of instructions of overhead -- when completions are present.  If completions aren't present, then fi_cq_sread() may be significantly slower in order to reset the wait object.

> 	Wait objects are not clearly defined as edge triggering or level
> triggered. They should be edge triggered. IOW, only new completions will
> signal the wait object.
> 
> 	I spent some more time reading through the slides. I think we need
> to make it clear that once a wait object has been signaled, it will not be
> reset until the corresponding CQ has been drained. That is indicated by
> fi_cq_sread() returning -FI_EAGAIN.
> 
> If the wait objects are edge-triggered then why would they need to be
> reset at all? Doesn't edge-triggered imply that the active state doesn't
> signifiy "signaled" anymore?

Please look at what verbs does.  That is at least one model that must be supported.

**Comment by bturrubiates** [comment] 2016-01-27 19:14
@shefty 
Is `fi_control(FI_GETWAIT...)` a valid operation on a waitset? The man pages mention using it with CQs and EQs, but not on waitsets. It seems that it's been implemented by several providers.

If this is a documentation issue I could document `fi_control` in the man page for `fi_wait`.

**Comment by shefty** [comment] 2016-01-27 19:31
I *think* this is a supportable feature, but I would hesitate to require it.  The problem is that the waitset may not use a single wait object.  On Linux, epoll could be used for fd's as a last resort.  But I don't know what you do for Solaris or FreeBSD or OS X.  I guess a provider could always just fail the call if it can't be supported.

Honestly, I didn't realize that this was not documented.  I implemented it in the UDP provider.  It's probably worth at least adding to the man page.

**Comment by bturrubiates** [comment] 2016-01-27 21:09
> I *think* this is a supportable feature, but I would hesitate to require it.  The problem is that the waitset may not use a single wait object.  On Linux, epoll could be used for fd's as a last resort.  But I don't know what you do for Solaris or FreeBSD or OS X.  I guess a provider could always just fail the call if it can't be supported.

Yeah, probably best case is to return `-FI_ENOSYS` or `-FI_ENOTSUPP`. 

> Honestly, I didn't realize that this was not documented.  I implemented it in the UDP provider.  It's probably worth at least adding to the man page.

Yeah I hadn't realized until now. I'll submit a PR to add some info to the man pages.

**Comment by bturrubiates** [comment] 2016-02-15 22:09
Summary of the [discussion](http://lists.openfabrics.org/pipermail/ofiwg/2016-February/001056.html) that took place on the mailing list: 
* Assuming correct application behavior, `fi_wait` should be implemented in a way that avoids infinite waiting and application spinning.
* Define conditions that must be met before waiting:
  * All associated CQs are empty
  * All associated EQs are empty
  * All associated counters have not incremented since last wait call
* Introduce a new API call `fi_trywait` that takes an array of `fid`s. This call only needs to be used when     using functions external to the API with a wait object retrieved with `fi_control`.
* `fi_trywait` would not only check if a wait can proceed but also prepare for it. This may include clearing events or resetting relevant resources. API calls will perform similar logic, but the location of the reset inside of those calls is left up to the implementation.
* The usage of `fi_cq_sread` may be limited to instances not making use of a waitset.
* When using `fi_wait` with an FD, the signaled queues can be retrieved using a pollset.

@shefty Does that look correct?

**Comment by shefty** [comment] 2016-02-16 18:06
This looks correct.  Note that an EQ cannot be associated with a poll set.  So, EQ handling requires a separate check.

We need to decide where trywait fits into the API.  Stand-alone, part of fid_fabric, or fid_domain?  And how it is hooked into the providers.

**Comment by bturrubiates** [comment] 2016-02-16 18:30
> This looks correct.  Note that an EQ cannot be associated with a poll set.  So, EQ handling requires a separate check.

Does this mean a new API call?

**Comment by shefty** [comment] 2016-02-16 19:16
Yes, I think it requires a new API call -- probably with the fabric object

**Comment by shefty** [comment] 2016-02-18 20:40
I'm trying to define trywait and understand how it could be implemented by the providers.  One issue that I see is what is expected from an application after trywait fails? Is there anything a provider can assume the app must do before calling trywait again?

Because trywait as discussed so far does not return any events, we can still end up in a situation where events could be left on a queue without the app being signaled, depending on what the app does here...

**Comment by bturrubiates** [comment] 2016-02-19 19:06
> I'm trying to define trywait and understand how it could be implemented by the providers. One issue that I see is what is expected from an application after trywait fails? Is there anything a provider can assume the app must do before calling trywait again?
> 
> Because trywait as discussed so far does not return any events, we can still end up in a situation where events could be left on a queue without the app being signaled, depending on what the app does here...

I'm not sure I understand what you mean. If there are events left on a queue, then the app has already been signaled. If the app calls `trywait` it should fail because it's unsafe to read if the queue hasn't been fully processed. In which case the app should reap the queues and re-attempt `trywait`.

**Comment by shefty** [comment] 2016-02-19 19:44
The problem is that the implementation of a trywait call may not be able to see if there is an item on the queue.  This is somewhat of a layering issue.  But consider the verbs case.  It requires that the app do this:

Reap the CQ
Arm the CQ for notifications
Reap the CQ again
Okay to block

The problem is how to implement trywait over this.  The trywait call can arm the CQ for notifications, but it cannot let the app actually block until the CQ is checked again.  Having trywait perform this check results in removing completions from the CQ, which then need to be stored somewhere, so the app can get them later.  In effect, it ends up layering a software CQ over the HW CQ.

This overhead can be avoided, but it depends on what the application must do when trywait says 'no, you can't wait yet'.

**Comment by shefty** [comment] 2016-02-19 20:08
I spoke with @a-ilango and asked him to look at this issue as well.

I think just adding an fi_trywait(fid_array...) call should work.  It will introduce a small amount of queuing in the verbs provider, but that's going to end up being there anyway.  And we can fix that by extending verbs with a call like ibv_cq_isempty() extension.  But from the application's perspective, things stay simple, and we want to drive this from the usability of the application.

I'll write up the man page description this afternoon and submit for review.

**Comment by xuywang** [comment] 2016-02-19 20:45
I am assuming fi_wait_set is level triggered for the above discussions. Let me know if my assumption is wrong.

Verbs has a mechanism to allow application to read the FD associated with the complete channel, which clear up the event that signaled the user application. This nicely decouples the cq completion and completion channel event. The read operation also provides an additional feature to notify application which CQs triggers the event. 

A fi_wait_set in a blocked state does not mean the associated CQs are empty (completions can still arrive at CQs after application resets the fi_wait_set but before polling the CQs). The same is true vice versa. After application clears the FD and before reading CQ, a new completion arrives and generates a new event. Then after application empties the CQ, the wait set is still not reset.

It is very hard for kernel component of provider to decide whether to reset the fi_wait_set based on whether the CQs are empty, which are present in userspace. It will incur significant performance penalty for fi_cq_read to drop to kernel to clear the FD assoicated with fi_wait_set. Additional checking need to be done when multiple CQs are associated with the same FD.

I think we need an API to clear the event in the queue. Does fi_try_wait actually returns an event if there is any?

**Comment by shefty** [comment] 2016-02-19 21:27
Trywait has not been defined.  :)  The goal of fi_wait or fi_trywait/select-poll combo is that they would not block if there is a completion to be read.  They would combine to act more like using select/poll, not ibv_get_comp_event/ibv_cq_read/ibv_cq_notify/ibv_ack_comp_event...

**Comment by xuywang** [comment] 2016-02-19 21:58
With select/poll, there is a read operation on the ready file descriptor to clear the readiness of FDs if the data are consumed by the read. 

Is there a corresponding operation for fi_trywait/select-poll?

**Comment by shefty** [comment] 2016-02-19 22:01
The app needs to call fi_cq_read/fi_eq_read.

**Comment by xuywang** [comment] 2016-02-19 22:12
From the perspective of provider implementation point of view: 

fi_cq_read normally only work on userspace, it incurs performance penalty to reset fi_wait object to drop to kernel.

Also considering multiple CQs share same fi_wait object, when and which fi_cq_read should reset the fi_wait object?

The implementation I see that can completely prevent races is for each fi_cq_read to drop to kernel, and be able to tell if other CQs associated with the same fi_wait object is empty. This is nearly impossible for usNIC provider.

**Comment by shefty** [comment] 2016-02-19 22:17
> fi_cq_read normally only work on userspace, it incurs performance penalty
> to reset fi_wait object to drop to kernel.

The assumption is that fi_cq_read stays in user space and only reads from the CQ.  It does not do anything with wait objects.

> Also considering multiple CQs share same fi_wait object, when and which
> fi_cq_read should reset the fi_wait object?

None - the wait object needs to be reset from the fi_trywait call.  Fi_trywait should fail if there are any completions on the CQ.

**Comment by xuywang** [comment] 2016-02-19 22:34
> None - the wait object needs to be reset from the fi_trywait call.  Fi_trywait should fail if there are any completions on the CQ.

Considering the following case, CQ1 and CQ2 are assoicated with wait_set
1. Completions arrives at CQ1 and CQ2
2. fi_wait(wait_set) return
3. fi_cq_read(CQ1) till empty
4. fi_cq_read(CQ2) till empty
5. fi_try_wait(wait_set) (assuming the following implementation)
5.1          if(empty(CQ1))
5.2             if(empty(CQ2))
5.3                  reset(wait_set)  drop-to-kernel

Notice that between 5.1 and 5.2, completions may arrive for CQ1, between 5.2 and 5.3, completions may arrive for CQ1 and CQ2, the implementation may unfortunately blocks application indefinitely.

Or do you have an idea of how provider implements fi_try_wait() without race?

**Comment by shefty** [comment] 2016-02-19 22:48
fi_trywait is only intended to be used with select/poll, not fi_wait.  fi_wait would need to implement an fi_trywait internally.

This is how fi_trywait would be implement with the verbs provider for a single CQ.  Multiple CQs would just introduce loops into the process:

1 reset fd -- drop to kernel to clear any old events
2 arm fd -- likely drop to kernel
3 if (cq is not empty) return -FI_EAGAIN

The CQ empty check needs to come after the reset of the fd.  You could put a check up front at step 0, but I'm assuming that the app has already cleared the CQ before calling fi_trywait, so we only add the check at step 3 to avoid races.

**Comment by shefty** [comment] 2016-02-20 01:16
See PR #1765 as the start of a fix.  I relabeled this as a bug, as the current interfaces cannot be guaranteed to support the use of wait objects with native calls.

**Comment by xuywang** [comment] 2016-02-21 08:02
I see.

So fi_wait should return when either the underlying wait object is signaled or one of the associated CQs has completions? 

Now I see that fi_wait is an analogy to select/poll, while CQ corresponds to fds. fi_wait should return if either through signal or one of its CQs is ready.

A fd based fi_wait implementation is something like this?
1 reset fd
2 arm fd
3 if cq is not empty return  (Check added here to prevent races)
4 poll/select

The man page of fi_wait says
fi_wait
Waits on a wait set until one or more of its underlying wait objects is signaled. 

I think this is a bit misleading. I thought the implementation should just wait for a fd/mutex/..., similar to what verbs does.

**Comment by shefty** [comment] 2016-02-21 17:02
Correct I think we want to follow the select/poll semantics as closely as possible.  Programmers will be familiar with that. In fact, I just spent the last 3-4 weeks holding email discussions with developers trying to program to verbs wait semantics and ending up with their application hanging.

The problem with fi_wait is that when it does end up waiting, it waits until the wait object is signaled, not until a completion is written to the CQ.  So on entry into fi_wait, if the CQ is not empty, the call returns immediately.  However, if the CQ is empty, the call waits until the wait object is signaled, which may be separate from an item being inserted into the CQ.

**Comment by xuywang** [comment] 2016-02-22 05:50
> However, if the CQ is empty, the call waits until the wait object is signaled, which may be separate from an item being inserted into the CQ.

For usNIC provider, when the wait object (underlying fd) is signaled, it is due to an interrupt being generated by a cq completion HW event. So application should be waked up to handle the new completion.

It's possible the completion may already be processed, in this case, the wake up is a spurious wakeup. Application just call fi_cq_read necessarily. But it won't result in application hang.

**Comment by xuywang** [comment] 2016-02-22 17:09
Please ignore my previous post. I just realized something on my way to work. :-)

fd based fi_wait can be implemented as
reset fd
arm fd
while cq is empty
     poll/select fd

This way when fi_wait returns, there is completion in cq.

I see that the API is indeed more application friendly than verbs.

**Comment by bturrubiates** [comment] 2016-03-03 23:22
@shefty 

So while looking at this more in depth today I noticed that it seems `fi_wait` returns `-FI_ETIMEDOUT` (this isn't documented in the man page) in the event of a timeout and `fi_cq_sread` returns `-FI_EAGAIN`. It makes sense to me for `fi_cq_sread` to return `-FI_EAGAIN` in the event of a timeout because that mirrors `fi_cq_read`. Should `fi_wait` also return `-FI_EAGAIN`? I'm fine with it the way it is, but would also be fine with all of them returning `-FI_EAGAIN`. I'll submit man page updates document appropriately.

**Comment by shefty** [comment] 2016-04-04 21:17
Fixed with trywait

**Closed by shefty** 2016-04-04 21:17 UTC
Labels: bug
