### ISSUE TITLE
prov/psm2: Support for finer-grained locking

### ISSUE THREAD

**Issue by rzambre** [ofiwg/libfabric#5080] opened 2019-06-10 14:41 UTC
I noticed that the `psm2` provider is only optimized for the `FI_THREAD_DOMAIN` threading attribute. So a multithreaded application or library (such as an MPI library) that uses multiple transmit/receive contexts within a scalable endpoint would not see any scaling in communication throughput even in the case where only one thread accesses a context. With the current implementation of the `psm2` provider, one would need to use a separate OFI domain per thread to scale communication throughput with increasing number of threads.

1) Could you verify my understanding?
2) Is there a plan to support finer-grained locking in the `psm2` provider as is the case in the `FI_THREAD_COMPLETION` threading attribute?

**Comment by j-xiong** [comment] 2019-06-13 19:34
While it's true that locking is currently only automatically optimized for FI_THREAD_DOMAIN, it doesn't mean applications with other threading models "would not see any scaling in communication throughput" with other threading models. The locks are only used to protect critical data structures, not serializing all the operations. In fact, one can try set FI_PSM2_LOCK_LEVEL=0 to see the best possible performance with all the locks disabled (or set FI_PSM2_LOCK_LEVEL=1 to only disable per context locks).

Automatic fine grain lock setting for FI_THREAD_COMPLETION is in the plan, but with low priority. There are some complications in the internal mechanism on how the objects are interacted so that it may not be completely safe to remove the per-context locks even if a context is only accessed by a single thread. Probably some restrictions will be added when this is implemented.

**Comment by rzambre** [comment] 2019-06-13 22:30
I see. My comment on scalable endpoint scaling performance was based on my experiment using `FI_PSM2_LOCK_LEVEL=1` with small message (8 bytes) transfers where I noticed all threads contending on the `av` lock (https://github.com/ofiwg/libfabric/blob/master/prov/psm2/src/psmx2.h#L1041). I didn't try with larger message sizes.

And yes, setting `FI_PSM2_LOCK_LEVEL=0` with 1 scalable endpoint (1 tx/rx context per thread) gives the same scaling performance as using `FI_THREAD_DOMAIN` (1 domain per thread) but that would be  incorrect semantics.

**Comment by j-xiong** [comment] 2019-06-13 22:38
The av lock is more difficult to remove since the av table is a domain-scope resource and it could be updated by dynamic connection establishment even if all addresses have been inserted in advance.

**Comment by hajimefu** [comment] 2019-06-14 17:02
Just trying to throw my random thoughts here; would it make sense to have a configuration option (such as envvar) to assert "this program will never use dynamic connection" so that the provider can avoid the av lock?

**Comment by j-xiong** [comment] 2019-06-14 17:12
Static connection is only available with FI_AV_MAP, which doesn't work with multiple endpoints or scalable endpoint.

**Comment by hajimefu** [comment] 2019-06-14 17:42
I see. Thank you for clarification.

**Comment by shefty** [comment] 2019-06-14 17:45
From the link, it looks like AV_MAP is already lockless in this regard.

Is it possible to optimistically perform this check without holding a lock?
```
    if (trx_ctxt->id && av->conn_info[trx_ctxt->id].epaddrs[idx])
```
If successful, retrun the epaddr.  If false, acquire the lock, re-check, and take the next steps?

**Comment by j-xiong** [comment] 2019-06-14 19:23
@shefty It's possible if all addresses have been inserted in advance (but how do we know?). Otherwise, during address insertion the tables could be reallocated. I looked into this in the past, but didn't come out with a good solution. Not sure if a read-write lock can really help the performance here.

**Comment by shefty** [comment] 2019-06-14 19:29
If the array can relocate, I agree, we need the lock.  In the optimal case, the lock is held over a very small window.  The app does know that it is accessing a single resource (AV in this case) from multiple threads, so it should expect some level of serialization.  Any other solution I can think of would likely have just as much overhead or more as using a lock, and would probably end up not working correctly.

**Comment by rzambre** [comment] 2019-08-02 14:44
> Static connection is only available with FI_AV_MAP, which doesn't work with multiple endpoints or scalable endpoint.

I am curious -- what is the reason `FI_AV_MAP` cannot work with multiple endpoints or scalable endpoints?

**Comment by hzhou** [comment] 2019-08-02 15:02
> Static connection is only available with FI_AV_MAP, which doesn't work with multiple endpoints or scalable endpoint.

@j-xiong Could you elaborate on that? 

I am working with @rzambre and currently experimenting with using multiple `fi_domain` each with scalable endpoints. It scales quite nicely with specific micro-benchmark. But as I trying with an actual application where the communication pattern is more ad-hoc, I hit this weird "bug" that a single `fi_tinjectdata` may take up to a couple seconds. A further dig narrowed down the culprit in `psmx2_av_query_sep`. 

The behavior is non-deterministic, but reproducible in my app. I am yet to be able to reproduce it in a micro-app.

Any insights?

This goes back to your comment, what is the reason that we can't use `FI_AV_MAP` in multiple endpoints? What is the dynamic nature in the address table that in a multiple endpoints case that prompts re-run `psmx2_av_query_sep` and why it causing it to "hang" for up to seconds?

**Comment by hzhou** [comment] 2019-08-02 15:31
... a further dig down reveal that `psmx2_av_query_sep` need send a am message to the dest -- which makes sense -- and it is the latency in that am message dominates the profile. That is in the midst of multiple on-going busy communication context, which again seems possible.

So back to the original question, it really become desirable to pre fetch all the av_map at init time, why that isn't possible? Is there way of hint/hack it for now?

**Comment by j-xiong** [comment] 2019-08-02 16:39
The mapped address in PSM2 depends on both local endpoint and remote endpoint and therefore is not unique for a destination if multiple endpoints are used. AV table is needed in order to hide the multiple mapping and create a unique address. Scalable endpoints are emulated with multiple endpoints and thus are in the same situation.

AV table is implemented with dynamic connection, with the expectation that not all connections are needed. It is possible to add option to per-establish all the connections, but per past experience, when scaled up, that can cause significant delay at application startup and shutdown.

**Comment by hzhou** [comment] 2019-08-02 16:55
Thx @j-xiong . That makes sense. I guess once the application knows its need, it can simply send collective ping message to pre-establish all the connections, that provides a better scalability than asking libfabric to always establish connections.

My only advice is to explain this underlying mechanism better in the libfabric man pages.

**Comment by shefty** [comment] 2020-08-27 17:13
@j-xiong -- I think it's safe to close this issue as 'will not address' at this point.

**Closed** 2020-08-27 18:31 UTC
