### ISSUE TITLE
prov/sockets: fi_compare_atomic doesn't honor FI_INJECT flag for compare data

### ISSUE THREAD

**Issue by agontarek** [ofiwg/libfabric#1959] opened 2016-04-12 18:46 UTC
When the FI_INJECT flag is set on a context, or provided to fi_compare_atomicmsg() as a flag, the compare data is not being copied to the provider maintained buffer when using the socket provider. The compare data should be copied to the inject buffer similar to what is being done with the buf data.

**Comment by jithinjosepkl** [comment] 2016-04-12 21:58
Yeah, we need to buffer the compare_buffer too. 

Also, another thing that @shefty pointed out is that the inject_size is per operation. So, the max inject size for buf and compare-buf in fi_compare_atomicmsg is half of max_inject_size. We need to add checking for this and clarify it in the manpages.

**Comment by shantonu** [comment] 2016-05-09 23:43
Sorry for the late reply. Can you please verify if the issue is resolved with PR #2016?

**Closed** 2016-05-18 00:12 UTC
