### ISSUE TITLE
rxm posts too many receives for core provider to handle

### ISSUE THREAD

**Issue by aingerson** [ofiwg/libfabric#5893] opened 2020-04-30 01:26 UTC
The rxm provider should only ever post the number of receives that the core provider can handle (preposts up to msg_info->rx_attr->size and reposts only when it gets a receive completion). But somehow it posts more than that, causing the core provider to return EAGAIN on the receive.

This is not an error/doesn't cause programs to fail but is an unnecessary extra receive post that fails which could be avoided.

**Comment by ooststep** [comment] 2020-05-07 17:02
I believe, as @shefty pointed out in #5899, this may have gotten fixed by some changes that were made in how messages get added to the repost ready list in some situations where they were not intended to.

Can you let me know the test you caught this with so i can verify?

**Comment by ooststep** [comment] 2020-05-07 18:24
I was able to reproduce this with the fi_bw test.  Looking a bit more at the code, there are places where new buffers are preemptively added to the repost ready list before the previous buffer is done processing and released. It appears the intent is to post new recv buffers so that incoming messages are not blocked while some potentially long running processing occurs, such as for rendezvous, or if unexpected messages come in.

Adjusting these scenarios so that we don't preemptively post new recv buffers prevents overloading the core provider but i'm not sure, yet, about the performance trade-offs.

**Comment by aingerson** [comment] 2020-05-07 18:35
I was verifying with the MPICH test suite test coll/reduce. I can send you the exact steps and patch I am using to verify over email if that's helpful.
Even if buffers are preemptively added to the repost ready list, the other receive that triggers this can be read off the cq so the core provider should be done with it so I'm not sure that's the whole issue. Though maybe because we haven't discarded the message that's still preventing the post. If this is the cause of the issue, then it's probably ok to ignore since there's probably a performance benefit. But I think there might be something else going on since I'm also seeing this overposting happening in the prepost_recv path. So I don't think that should have to do with the preemptive posting, should it?
Feel free to message me to discuss/help with the reproducing.

**Comment by shefty** [comment] 2020-05-07 18:42
I thought in the cases where the new buffers were posted, the buffer just consumed was not.

**Comment by aingerson** [comment] 2020-05-07 19:17
The buffer just consumed is not reposted; rxm allocates/gets a new, free buffer and adds it to the repost_ready_list to be reposted next

**Closed** 2020-10-01 19:58 UTC
