### ISSUE TITLE
daos: tcp;ofi_rxm: failure to connect to endpoint if previous connection is not successful

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#6682] opened 2021-04-06 22:00 UTC
Provider: tcp;ofi_rxm

In the test we start client and server asynchronously where client tries 'pinging' server via RPC until server responds, at which point client continues the actual test execution. In this situation it is expected for clients first few pings to be errors, as server takes few seconds to launch up/setup its endpoints.

This scenario was working previously with ofi v1.11.1 (also re-verified it), however fails now with 1.12.0rc1 and 1.12.0

In case of latest ofi (1.12.0) once the client fails to connect to the address, all subsequent connections fail as well.
The error during initial connect failure on the client is:
libfabric:100097:tcp:ep_ctrl:tcpx_cm_send_req():385<warn> connection failure
libfabric:100097:ofi_rxm:ep_ctrl:rxm_eq_readerr():84<warn> fi_eq_readerr: err: Unknown error -111 (-111), prov_err: Success (0)

After which all subsequent attempts to connect to server time out but do not produce any additional errors.

The same test works fine with sockets provider.
This test also works fine if the client is started after all servers are initialized/ready to accept connections.

To reproduce the issue. At the top of daos install tree run the following script (modify SERVER_HOST and CLIENT_HOST hostnames as needed)

`export OFI_INTERFACE=eth0
export CRT_PHY_ADDR_STR="ofi+tcp;ofi_rxm"
SERVER_HOST='wolf-55'
CLIENT_HOST='wolf-55'

export CRT_LAUNCH="install/bin/crt_launch"

export NO_PMIX_SERVER="install/lib/daos/TESTING/tests/no_pmix_launcher_server"
export NO_PMIX_CLIENT="install/lib/daos/TESTING/tests/no_pmix_launcher_client"
export FI_LOG_LEVEL=warn
export ORTE_ENVARS="-x D_LOG_FLUSH=WARN -x PATH -x D_LOG_MASK=WARN -x OFI_DOMAIN -x CRT_PHY_ADDR_STR -x OFI_INTERFACE"

set -x
orterun -np 5 -H ${SERVER_HOST}:7 --map-by node  ${ORTE_ENVARS} ${CRT_LAUNCH} -e ${NO_PMIX_SERVER} : -H ${CLIENT_HOST}:7 -np 1 ${ORTE_ENVARS} -x FI_LOG_LEVEL ${CRT_LAUNCH} -c -e ${NO_PMIX_CLIENT}
`

**Comment by frostedcmos** [comment] 2021-04-07 00:11
I've narrowed it a bit more down. This test worked fine with v1.11.2  but fails on a next tag of v1.12.0rc1

**Comment by frostedcmos** [comment] 2021-08-04 17:49
Retried with 7d6d2a13411f8b5e793939493ed6e9f8b1c6a887 and the issue is still present there. 
This time it is a flood of warnings of "libfabric:68325:tcp:ep_ctrl:tcpx_cm_send_req():390<warn> connection failure" followed by rpcs timing out.

To double check, reverted back to v1.11.1 and reproducer passes on the same system with same setup.

**Comment by shefty** [comment] 2021-09-13 18:45
With fabtests, if I start the client prior to the server, the client will repeatedly fail to connect until the server is started.  Once the server starts, the connection completes and the test succeeds.  The failure output that you're seeing is expected, since the connections are being retried repeatedly.  We currently don't have any mechanism to rate limit warnings.

We'll need a reproducer for this.  If the problem were simple, fabtests should have worked for a reproducer, but it's not sufficient.

**Comment by frostedcmos** [comment] 2021-09-16 02:18
Reproducer along with script to run it is provided in the initial post.
Retried this with latest ofi as of 

"commit df5e8edfa75056b5d1cab1b21cb921d3ec8de349
Merge: 10941c1 aefc898
Author: Sean Hefty <sean.hefty@intel.com>
Date:   Mon Sep 13 09:06:35 2021 -0700

    Merge pull request #7052 from shefty/main
"

The problem is still present with tcp;rxm. verbs;rxm and sockets work fine using the reproducer above.

**Comment by shefty** [comment] 2021-09-16 17:18
I was looking for a reproducer that wasn't run the application.

**Comment by shefty** [comment] 2021-10-01 00:55
Resolved with changes now in main

**Closed by shefty** 2021-10-01 00:55 UTC
Labels: high priority
