### ISSUE TITLE
DAOS: unable to run dual-server/dual-nic setup with tcp;ofi_rxm

### ISSUE THREAD

**Issue by frostedcmos** [ofiwg/libfabric#6942] opened 2021-07-21 17:44 UTC
We are running into a strange problem with tcp;ofi_rxm provider when trying to run 2 servers on the same node, one on each interface.
Normally for verbs;ofi_rxm we set following settings, allowing servers to communicate with each other:

$ sudo sysctl -w net.ipv4.conf.all.accept_local=1
$ sudo sysctl -w net.ipv4.conf.all.arp_ignore=2
$ sudo sysctl -w net.ipv4.conf.<ifaces>.rp_filter=2

The same configuration does not seem to be working when we try tcp;ofi_rxm provider.

In the outputs below, we start ‘dual_iface_server’ which is a simple server that forks two copies of itself, each listening on its own interface. Once both servers are up, they exchange ‘ping’ rpc and exit.
As you can see with verbs it works fine (also works fine with sockets), but we end up timing out rpcs with tcp.

Example run with verbs:
aaoganez@wolf-21 daos> ./install/lib/daos/TESTING/tests/dual_iface_server -p 'ofi+verbs;ofi_rxm' -i 'ib0,ib1' -d 'mlx5_0,mlx5_1'
----------------------------------------
Provider: 'ofi+verbs;ofi_rxm'
Interface0: 'ib0' Domain0: 'mlx5_0'
Interface1: 'ib1' Domain1: 'mlx5_1'
File to transfer: 'none'
----------------------------------------

SRV [rank=1 pid=46383]  Starting server rank=1
SRV [rank=0 pid=46384]  Starting server rank=0
SRV [rank=1 pid=46383]  my_rank=1 uri=ofi+verbs;ofi_rxm://192.168.101.21:32337
SRV [rank=0 pid=46384]  my_rank=0 uri=ofi+verbs;ofi_rxm://192.168.100.21:31337
SRV [rank=1 pid=46383]  Other servers uri is 'ofi+verbs;ofi_rxm://192.168.100.21:31337'
SRV [rank=0 pid=46384]  Other servers uri is 'ofi+verbs;ofi_rxm://192.168.101.21:32337'
SRV [rank=1 pid=46383]  Ping successful to rank=0 tag=0
SRV [rank=0 pid=46384]  Ping successful to rank=1 tag=0

Example run with tcp:
aaoganez@wolf-21 daos> ./install/lib/daos/TESTING/tests/dual_iface_server -p 'ofi+tcp;ofi_rxm' -i 'ib0,ib1' -d 'ib0,ib1'       
----------------------------------------
Provider: 'ofi+tcp;ofi_rxm'
Interface0: 'ib0' Domain0: 'ib0'
Interface1: 'ib1' Domain1: 'ib1'
File to transfer: 'none'
----------------------------------------

SRV [rank=1 pid=46508]  Starting server rank=1
Starting server rank=0
SRV [rank=1 pid=46508]  my_rank=1 uri=ofi+tcp;ofi_rxm://192.168.101.21:32337
SRV [rank=0 pid=46509]  my_rank=0 uri=ofi+tcp;ofi_rxm://192.168.100.21:31337
SRV [rank=1 pid=46508]  Other servers uri is 'ofi+tcp;ofi_rxm://192.168.100.21:31337'
SRV [rank=0 pid=46509]  Other servers uri is 'ofi+tcp;ofi_rxm://192.168.101.21:32337'
crt  EMRG src/cart/crt_utils.c:584 crtu_sem_timedwait() Assertion 'rc == 0' failed: sem_timedwait() failed at line 421 rc: -1
crt  EMRG src/cart/crt_utils.c:584 crtu_sem_timedwait() Assertion 'rc == 0' failed: sem_timedwait() failed at line 421 rc: -1

Example run with sockets:
aaoganez@wolf-21 daos> ./install/lib/daos/TESTING/tests/dual_iface_server -p 'ofi+sockets' -i 'ib0,ib1' -d 'ib0,ib1'
----------------------------------------
Provider: 'ofi+sockets'
Interface0: 'ib0' Domain0: 'ib0'
Interface1: 'ib1' Domain1: 'ib1'
File to transfer: 'none'
----------------------------------------

SRV [rank=1 pid=46711]  Starting server rank=1
SRV [rank=0 pid=46712]  Starting server rank=0
SRV [rank=1 pid=46711]  my_rank=1 uri=ofi+sockets://192.168.101.21:32337
SRV [rank=0 pid=46712]  my_rank=0 uri=ofi+sockets://192.168.100.21:31337
SRV [rank=1 pid=46711]  Other servers uri is 'ofi+sockets://192.168.100.21:31337'
SRV [rank=1 pid=46711]  Ping successful to rank=0 tag=0
SRV [rank=0 pid=46712]  Other servers uri is 'ofi+sockets://192.168.101.21:32337'
SRV [rank=0 pid=46712]  Ping successful to rank=1 tag=0

To reproduce the problem:
Clone daos from master and compile
from the daos/ directory run
./install/lib/daos/TESTING/tests/dual_iface_server -p 'ofi+tcp;ofi_rxm' -i 'ib0,ib1' -d 'ib0,ib1'  

(adjust -i params if using different interfaces, and similarly adjust -d param if using different domains)

**Comment by j-xiong** [comment] 2021-07-26 20:41
Trying to build daos from source is not easy, with tons of dependencies that may be unrelated to things that we care about here. Is there a way to build a minimal set of components that can be used to reproduce the issue?

I did created a simple OFI program that mimic the behavior of the dual_iface_server test, i.e., two server processes using different NIC and doing a pingpong with fi_send and fi_recv. However, the test ran just fine with rxm/tcp over two nics. So the issue could be well in the details on how the communication happens.

**Comment by frostedcmos** [comment] 2021-08-04 17:38
Retried with https://github.com/ofiwg/libfabric/commit/7d6d2a13411f8b5e793939493ed6e9f8b1c6a887
The issue is still present with tcp;rxm

**Comment by j-xiong** [comment] 2021-08-04 17:42
That commit only fixes the regression. This issue is still being investigated.

**Comment by j-xiong** [comment] 2021-08-12 03:57
I have identified the cause, but the fix is not going to be easy.

The interface selection, which mapped to the "src_addr" field of fi_info, only applies to the passive side of the TCP connection (i.e. the side that calls accept()). The active side gets its address assignment automatically based on how it can reach the other side. In the dual-nic example here, the resulting address is on the same interface as the passive side. The tcp provider calls getpeername() over the connected socket to retrieve the peer address and use it to identify the source of a received message. This address, apparently is different from the pre-calculated address based on the interface selection. As the result, the incoming messages can't match the pre-posted receives that require specific source.

Some rework on the the tcp provider connection manager will be needed to resolve the issue.

**Comment by shefty** [comment] 2021-09-09 19:52
The problem may be at the rxm level, vs tcp.  tcp appears to be providing the correct address relative to the connection that was actually formed.  RxM exchanges the listening port number as part of the CM protocol, and it uses that to construct the peer's address.  I think the following situation is needed:

1. An rxm ep address should match the listening socket address
2. The rxm ep should request a src IP address that matches its local listening socket for any msg ep.  The port address can be a wildcard.
3. rxm ep should connect to the peer's passive socket address.  That address should be the dest_addr for the msg ep.
4. tcp should bind a socket to specified src address prior to calling connect.
5. rxm needs to use the passive socket port number as the local rxm ep address.  This is exchanged as part of the rxm CM protocol.

I'll try to confirm this flow.

**Comment by shefty** [comment] 2021-09-10 00:45
In rxm_open_core_res(), there's the following code:
```
	ret = ofi_get_core_info(domain->util_domain.fabric->fabric_fid.api_version,
				NULL, NULL, 0, &rxm_util_prov, ep->rxm_info,
				NULL, rxm_info_to_core, &ep->msg_info);
...
	ret = rxm_listener_open(ep);
	if (ret)
		goto err2;

	/* Zero out the port as we will create multiple MSG EPs for a
	 * single RXM EP, and we don't want address conflicts.
	 */
	if (ep->msg_info->src_addr)
		ofi_addr_set_port(ep->msg_info->src_addr, 0);
```
This suggests that the msg_info used to create the msg ep's may not have the src_addr set.  If that's the case, then the msg ep src_addr will be based on the dest_addr.  That correlates with the bug report and comment from @j-xiong .

What I haven't been able to determine is why msg_info->src_addr would not be set.  ofi_get_core_info() should copy the src_addr from ep->rxm_info, suggesting that rxm_info->src_addr is null.  Ideally the if() check should be an assert(), with rxm_info->src_addr set to the address of the rdm ep, and that copied to the msg_info->src_addr.

It should be straightforward to call fi_getname() after enabling the rdm ep and save the src_addr.  But I want to confirm that msg_info->src_addr is not set in the above path and understand why not, if not.

**Comment by shefty** [comment] 2021-09-10 17:36
I spoke with @j-xiong, and I'm working on what I believe will be a fix.

**Comment by shefty** [comment] 2021-09-10 23:41
#7052 targets a fix for this issue.  That fix has not been tested with a reproducer or verified with DAOS yet.

**Comment by frostedcmos** [comment] 2021-09-11 00:13
I've verified locally that #7052 appears to fix the issue with the original reproducer:

`
```
aaoganez@wolf-21 daos> ./install/lib/daos/TESTING/tests/dual_iface_server -p 'ofi+tcp;ofi_rxm' -i 'ib0,ib1' -d 'ib0,ib1'
----------------------------------------
Provider: 'ofi+tcp;ofi_rxm'
Interface0: 'ib0' Domain0: 'ib0'
Interface1: 'ib1' Domain1: 'ib1'
File to transfer: 'none'
----------------------------------------

SRV [rank=1 pid=40426]  Starting server rank=1
SRV [rank=0 pid=40427]  Starting server rank=0
SRV [rank=1 pid=40426]  my_rank=1 uri=ofi+tcp;ofi_rxm://192.168.101.21:32337
SRV [rank=0 pid=40427]  my_rank=0 uri=ofi+tcp;ofi_rxm://192.168.100.21:31337
SRV [rank=1 pid=40426]  Other servers uri is 'ofi+tcp;ofi_rxm://192.168.100.21:31337'
SRV [rank=1 pid=40426]  Ping successful to rank=0 tag=0
SRV [rank=0 pid=40427]  Other servers uri is 'ofi+tcp;ofi_rxm://192.168.101.21:32337'
SRV [rank=0 pid=40427]  Ping successful to rank=1 tag=0
```

`

**Closed** 2021-09-13 16:06 UTC
