### ISSUE TITLE
verbs: inject size is being misreported

### ISSUE THREAD

**Issue by bturrubiates** [ofiwg/libfabric#1079] opened 2015-06-16 22:00 UTC
It seems the inject size for the verbs provider is being misreported and can lead to crashes. Reported by @zakattacktwitter on #1044. 

> Hi, inject_size is being reported and used by the verbs provider. That said, it has some bugs. The current code does not consider the size of the header along with the message size, triggering crashes when trying to send. For example my setup reports 74 bytes for inject_size, but if I send a msg between 33 bytes and 74 it will crash, anything 32 bytes and below is successfully injected and anything above 74 works fine.

@a-ilango

**Comment by a-ilango** [comment] 2015-06-16 22:02
@bturrubiates Thanks, will take a look at this.

**Comment by a-ilango** [comment] 2015-06-16 23:28
@zakattacktwitter, What is the header that you're referring to? I couldn't reproduce the issue that you're seeing. My setup reports a max inject size of 88. I ran fi_msg_pingpong with various sizes between 16 and 120 and I didn't see any crash. What test are you running?

**Comment by zakattacktwitter** [comment] 2015-06-18 16:18
I am working on setting up an example for you. Sorry for the delay!

**Comment by bturrubiates** [comment] 2015-06-30 17:22
@zakattacktwitter Any updates?

**Comment by zakattacktwitter** [comment] 2015-06-30 17:38
Hi,

I was not registering the memory with fi_mr_reg before sending a message.
This unregistered memory send actually worked for 32 bytes or less. I
haven’t had time to make a nice sample to demonstrate this. I imagine its
mostly a user error to not register the memory before trying to send. Since
adding fi_mr_reg to all my send buffers everything has worked perfectly.

Thanks,
Zak

**Comment by a-ilango** [comment] 2015-07-07 17:16
Thanks for the update! Can we close this issue since it is an app error?

**Closed** 2015-07-07 17:20 UTC
