### ISSUE TITLE
prov/rxm,man/fi_rxm: applications with manual progress will hang on first data transfer without appropriate calls to fi_cq_read

### ISSUE THREAD

**Issue by tonyzinger** [ofiwg/libfabric#4425] opened 2018-09-20 17:20 UTC
The following file contains the test case fi_info information and Libfabric debug messages that are displayed starting at the call to FI_WRITE until it hung.  The test case was killed at this point.

[FI_WRITE_hang.txt](https://github.com/ofiwg/libfabric/files/2402361/FI_WRITE_hang.txt)

**Comment by a-ilango** [comment] 2018-09-20 20:28
@tonyzinger can you check if the test progresses the CQ on all ranks? RxM would require manual progress for data from applications if the app doesn't explicitly request auto progress.

**Comment by tonyzinger** [comment] 2018-09-20 20:39
@a-ilango The test will process CQ events after it returns from the FI_WRITE call.  However, in this case, the test is still in the FI_WRITE call.  It has not returned from the FI_WRITE call.   All of the ranks are hung at the same point.  I print out a debug message when the FI_WRITE returns with or without an error and this message has not been printed.

Is there something that you would like me to try?

**Comment by a-ilango** [comment] 2018-09-20 20:52
Hmm. I didn't realize it was hanging *in* fi_write call. What threading level does the test use? Can you please run the test with FI_LOG_LEVEL=debug (ensure libfabric is built with --enable-debug) and share the logs?

Is this a specific MPI benchmark?

**Comment by a-ilango** [comment] 2018-09-21 16:53
Can you share your test / reproducer? I'm not able to reproduce the issue with the tests or benchmarks I have.

**Comment by tonyzinger** [comment] 2018-09-21 20:43
I will look at either giving you a simplified test case or describe what the API calling sequences are in the test along with the various libfabric settings that are used..

**Comment by jswaro** [comment] 2018-10-08 17:05
It seems to happen specifically with 3072b7c0cf87f0c692a07bba0aaf09006ab5bc2a

**Comment by shefty** [comment] 2018-10-08 17:11
What is the progress model used by the app?

**Comment by jswaro** [comment] 2018-10-08 17:14
Based on what I'm seeing on Tony's log file, it seems like he is using auto progress for control, and manual for data.

**Comment by jswaro** [comment] 2018-10-08 17:33
@a-ilango @shefty 
So I started looking here. 

https://github.com/ofiwg/libfabric/commit/3072b7c0cf87f0c692a07bba0aaf09006ab5bc2a#diff-b6fda6081c785045cefa49f0db7e2b3dL619

Shouldn't connection management be driven by the control progress model rather than the data progress model of the application?

> Control progress indicates the method that the provider uses to make progress on asynchronous control operations.  Control operations are functions which do not directly involve the transfer of application data between endpoints.  They include address vector, memory registration, and connection management routines.

**Comment by a-ilango** [comment] 2018-10-08 17:36
Posting an RMA shouldn't affect event queue entry generation. It would help to identify where exactly is the hang. Is this in rxm write call or ibv_post_send? Calling fi_write for rxm should return -FI_EAGAIN until the connection is established. 

> Shouldn't connection management be driven by the control progress model rather than the data progress model of the application?

RDM endpoints don't expose connections to the app, hence we tie it with data progress.

**Comment by a-ilango** [comment] 2018-10-08 17:37
Also, the connections are on-demand when trying to send the data.

**Comment by jswaro** [comment] 2018-10-08 17:46
Fair enough, so what should an application do with respect to connection management if they attempt to post an RMA operation but fail?

Can we reasonably expect application to poll a CQ when no data is posted? They do not know that the underlying systems haven't done the necessary work to ensure that endpoints have been connected (if needed)?

I think at this point, all the application is aware of is the following:

- Necessary structures have been created and configured
- An fi_write call has made but has failed with EAGAIN

Given that it is the first data transfer that the application has ever made, should the application be expected to call fi_cq_read (or other functions) in this case? Is that message consistent with the man pages so that applications have the correct guidance?

**Comment by a-ilango** [comment] 2018-10-08 17:52
> Given that it is the first data transfer that the application has ever made, should the application be expected to call fi_cq_read (or other functions) in this case? Is that message consistent with the man pages so that applications have the correct guidance?

Yes. If a data transfer operation fails, the app has to poll the CQ, especially if the data progress model is manual.

The ERRORS section in https://ofiwg.github.io/libfabric/master/man/fi_msg.3.html provides more details.

**Comment by jswaro** [comment] 2018-10-08 17:58
> The ERRORS section in https://ofiwg.github.io/libfabric/master/man/fi_msg.3.html provides more details.

I understand that error section well, and I was debating whether to reference it. 

As an application writer, why would/should I expect FI_EAGAIN when the data structures have been freshly allocated, and no transactions should be pending? It is an odd behavior. If that is the recommendation, then sure -- easy enough to fix in Tony's application and would be an issue with the upper layer rather than the provider.  However, maybe this needs a note in the fi_rxm man page so that it is clear that something like this should be done even if the structures have never been used.

**Comment by shefty** [comment] 2018-10-08 18:01
The local side may be waiting for flow control credits from the peer before it can begin the transfer.  That is essentially what is happening in this case.  The connection sets up the necessary credits for the transfer to occur.

**Comment by a-ilango** [comment] 2018-10-08 18:13
> However, maybe this needs a note in the fi_rxm man page so that it is clear that something like this should be done even if the structures have never been used.

I can add a note in the rxm man page.

**Comment by jswaro** [comment] 2018-10-08 18:19
Sounds good. I'll help Tony with the modifications to his test suite, and we can use this issue to track the note to the RXM man page, or just close this.

**Comment by a-ilango** [comment] 2018-10-08 18:30
> we can use this issue to track the note to the RXM man page

Sounds good.

**Closed** 2018-10-08 20:09 UTC
