### ISSUE TITLE
regression: f7819ca to 66d0475, getinfo failing

### ISSUE THREAD

**Issue by jswaro** [ofiwg/libfabric#5665] opened 2020-02-24 22:54 UTC
commit fa08835bc7b67fb24e60f8f041426e94843dea5c (origin/master, origin/HEAD, master)
Merge: f7819caa2 66d0475ed
Author: aingerson <alexia.ingerson@intel.com>
Date:   Mon Feb 24 12:44:21 2020 -0800

    Merge pull request #5628 from aingerson/directed_recv

    fabtests/getinfo_test, prov/psm2, rxm, rxd, shm, udp, verbs, sockets, efa: test capability sets

Tests running fi_send* and fi_inject* variants are failing now after the recent merge to master. I'll post more information tomorrow.

**Comment by jswaro** [comment] 2020-02-24 22:55
@aingerson @shefty

**Comment by jswaro** [comment] 2020-02-24 22:55
Our testing only runs with ofi-rxm+verbs to help narrow it down.

**Comment by shefty** [comment] 2020-02-24 23:05
It would help to know what tests you see failing.  The fabtests are passing with verbs + rxm locally for us.

**Comment by jswaro** [comment] 2020-02-25 17:16
> It would help to know what tests you see failing. 

Understood. I wanted to put out the notice last night, then finish adding details this morning. 

Fabtests are passing, but multiple applications are failing for us. I have a UPC application that fails to find a provider, in additional to our internal tests (SFT, @tonyzinger). 

I can't provide the SFT tests, but I can probably provide the upc test code. MPI does pass. I don't believe we normally run fi_ubertest, but that might be an option. I'll talk to Tony about a reproducer. 

If I get some spare cycles today, I'll look into a patch, but I wanted to post this first in the event that you or @aingerson  could spot the fix easily.

**Comment by jswaro** [comment] 2020-02-25 17:18
> It would help to know what tests you see failing. 

Understood. I wanted to put out the notice last night, then finish adding details this morning. 

Fabtests are passing, but multiple applications are failing for us. I have a UPC application that fails to find a provider, in additional to our internal tests (SFT, @tonyzinger). 

I can't provide the SFT tests, but I can probably provide the upc test code. MPI does pass. I don't believe we normally run fi_ubertest, but that might be an option. I'll talk to Tony about a reproducer. 

If I get some spare cycles today, I'll look into a patch, but I wanted to post this first in the event that you or @aingerson  could spot the fix easily.

**Comment by tonyzinger** [comment] 2020-02-25 18:25
Here is the hints information that the SFT Message test is using to select a provider via the fi_getinfo API:
fi_info:
    caps: [ FI_MSG, FI_RECV, FI_SEND, FI_DIRECTED_RECV ]
    mode: [ FI_CONTEXT, FI_LOCAL_MR ]
    addr_format: FI_FORMAT_UNSPEC
    src_addrlen: 0
    dest_addrlen: 0
    src_addr: (null)
    dest_addr: (null)
    handle: (nil)
    fi_tx_attr:
        caps: [ FI_MSG, FI_SEND, FI_SOURCE, FI_DIRECTED_RECV ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [  ]
        comp_order: [ FI_ORDER_NONE ]
        inject_size: 0
        size: 0
        iov_limit: 0
        rma_iov_limit: 0
    fi_rx_attr:
        caps: [ FI_MSG, FI_RECV, FI_SOURCE, FI_DIRECTED_RECV ]
        mode: [  ]
        op_flags: [  ]
        msg_order: [  ]
        comp_order: [ FI_ORDER_NONE ]
        total_buffered_recv: 0
        size: 0
        iov_limit: 0
    fi_ep_attr:
        type: FI_EP_RDM
        protocol: FI_PROTO_UNSPEC
        protocol_version: 0
        max_msg_size: 0
        msg_prefix_size: 0
        max_order_raw_size: 0
        max_order_war_size: 0
        max_order_waw_size: 0
        mem_tag_format: 0x0000000000000000
        tx_ctx_cnt: 0
        rx_ctx_cnt: 0
        auth_key_size: 0
    fi_domain_attr:
        domain: 0x0
        name: (null)
        threading: FI_THREAD_UNSPEC
        control_progress: FI_PROGRESS_UNSPEC
        data_progress: FI_PROGRESS_UNSPEC
        resource_mgmt: FI_RM_UNSPEC
        av_type: FI_AV_TABLE
        mr_mode: [ FI_MR_LOCAL, FI_MR_VIRT_ADDR, FI_MR_ALLOCATED, FI_MR_PROV_KEY ]
        mr_key_size: 0
        cq_data_size: 0
        cq_cnt: 0
        ep_cnt: 0
        tx_ctx_cnt: 0
        rx_ctx_cnt: 0
        max_ep_tx_ctx: 0
        max_ep_rx_ctx: 0
        max_ep_stx_ctx: 0
        max_ep_srx_ctx: 0
        cntr_cnt: 0
        mr_iov_limit: 0
    caps: [  ]
    mode: [  ]
        auth_key_size: 0
        max_err_data: 0
        mr_cnt: 0
    fi_fabric_attr:
        name: (null)
        prov_name: verbs;ofi_rxm
        prov_version: 0.0
        api_version: 1.7
    nic_fid: (nil)

**Comment by jswaro** [comment] 2020-02-25 21:40
Results: 
```
crayadm@cn1:/scratch/jswaro> gcc test.c -I$PWD/install/libfabric/include -lfabric -L$PWD/install/libfabric/lib -o tester
crayadm@cn1:/scratch/jswaro> LD_LIBRARY_PATH=$PWD/install/libfabric/stable/lib ./tester
prov=verbs;ofi_rxm
crayadm@cn1:/scratch/jswaro> LD_LIBRARY_PATH=$PWD/install/libfabric/master/lib ./tester
tester: test.c:36: main: Assertion `ret == FI_SUCCESS' failed.
Aborted (core dumped)
```

test.c
```c
#include <stdio.h>
#include <assert.h>

#include "rdma/fabric.h"
#include "rdma/fi_errno.h"

int main(int argc, char** argv) {
	int ret;

	struct fi_info *hints, *info;

	hints = fi_allocinfo();

	hints->caps = FI_MSG | FI_RECV | FI_SEND | FI_DIRECTED_RECV;
	hints->mode = FI_CONTEXT | FI_LOCAL_MR;
	hints->addr_format = FI_FORMAT_UNSPEC;

	hints->fabric_attr->prov_name = "ofi_rxm;verbs";
	hints->fabric_attr->api_version = FI_VERSION(1,7);

	hints->domain_attr->av_type = FI_AV_TABLE;
	hints->domain_attr->mr_mode = FI_MR_LOCAL | FI_MR_VIRT_ADDR | FI_MR_ALLOCATED | FI_MR_PROV_KEY;

	hints->ep_attr->type = FI_EP_RDM;
	hints->ep_attr->protocol = FI_PROTO_UNSPEC;

	hints->tx_attr->caps = FI_MSG | FI_RECV | FI_SEND | FI_DIRECTED_RECV;
	hints->tx_attr->comp_order = FI_ORDER_NONE;

	hints->rx_attr->caps = FI_MSG | FI_RECV | FI_SEND | FI_DIRECTED_RECV;
	hints->rx_attr->comp_order = FI_ORDER_NONE;



	ret = fi_getinfo(FI_VERSION(FI_MAJOR_VERSION, FI_MINOR_VERSION), NULL, NULL, 0, hints, &info);
	assert(ret == FI_SUCCESS);

	for (struct fi_info *current = info; current = current->next; current != NULL) {
		fprintf(stderr, "prov=%s\n", current->fabric_attr->prov_name);
	}

}```

**Comment by jswaro** [comment] 2020-02-25 21:41
I'll look into later tomorrow, but it's here if you want a reproducer.

**Comment by aingerson** [comment] 2020-02-26 14:43
Sorry for the late reply, I was OOO yesterday.
One thing that immediately jumps out at me is that it seems like your test is requesting tx_attr->caps FI_DIRECTED_RECV which is only an rx_attr. The patch that was merged fixed this in the rxm provider.

**Comment by tonyzinger** [comment] 2020-02-26 15:34
In the SFT Message test case, I have the following caps set in the hints:
     caps: [ FI_MSG, FI_RECV, FI_SEND ]
     fi_tx_attr: caps: [ FI_MSG, FI_SEND, FI_SOURCE ]
     fi_rx_attr: caps: [ FI_MSG, FI_RECV, FI_SOURCE ]
And it still does not find a provider.

**Comment by aingerson** [comment] 2020-02-26 15:37
@tonyzinger FI_SOURCE is also only a receive side capability

**Comment by tonyzinger** [comment] 2020-02-26 15:52
@aingerson Removing the FI_SOURCE capability from the fi_tx_attr resolved the problem.  Along with removing FI_DIRECTED_RECV from the fi_tx_attr caps. The SFT Message test is now passing again.  Thanks for the help.

**Comment by jswaro** [comment] 2020-02-26 16:10
I see, test case failure on our end. I need to reach out to the UPC contributor and see if they are doing something similar.

**Comment by shefty** [comment] 2020-02-26 16:21
Yeah, the definition of which caps were tx vs rx was not clearly defined before.  We're trying to fix that.

**Comment by jswaro** [comment] 2020-02-26 16:25
Thanks for the help and explanation of the changes. Our tests should be passing again and the UPC contributor has been notified of the changes so that they can fix them if they haven't already by now.

**Comment by shefty** [comment] 2020-02-26 18:03
Re-opening issue.  We want to fix the tx/rx caps because we are seeing confusion.  But if the change is breaking current applications, then we may want to re-think the approach.

**Comment by shefty** [comment] 2020-02-27 17:28
What would help is to know whether there are real applications in the field that are now setting the wrong tx/rx caps bits as part of their hints.  If they are, the latest code will now fail their getinfo calls.

We can 'fix' this by ignoring those invalid bits, rather than checking that they are not set.

**Comment by jswaro** [comment] 2020-02-27 17:55
I can ask around. I do know that our SHMEM contributors reported the same regression yesterday, so SHMEM is also affected by this.

**Comment by jswaro** [comment] 2020-02-27 18:02
An option: We could issue a statement -- in the man pages or release notes -- saying that invalid TX/RX mode bits will be ignored for 1.10, and we expect to reject invalid bits by the next release. It gives consumers a chance to respond to the change, while we prepare the changes and make sure the changes do what we need/expect them to do. However, there are no guarantees that the release notes will be read.

Another option: Ignore the bits unless we have some 'strict checking' option, allowing provider discovery to fail under strict, but ignore otherwise. 

Another option: Add warnings to the provider discovery code which could inform consumers that they are requesting invalid options in the tx/rx attributes.

**Comment by shefty** [comment] 2020-02-27 18:03
I like the last option.  We can ignore the bits, but display a warning that invalid bits were requested.

**Comment by jswaro** [comment] 2020-02-27 18:03
:+1:

**Comment by shefty** [comment] 2020-03-06 19:17
Please see if #5710 fixes the regression.

**Comment by jswaro** [comment] 2020-03-06 19:21
I've added the Cray CI tag, and kicked off the build.

**Closed** 2020-03-09 20:20 UTC
