### ISSUE TITLE
prov/verbs: Timeout after scaling up to 64 client procs on 16 nodes to 4 server procs on 1 node or 8(2) on Polaris Slingshot 10

### ISSUE THREAD

**Issue by Zhang690683220** [ofiwg/libfabric#8482] opened 2023-02-10 01:19 UTC
**Describe the bug**
I'm on the Polaris system at ALCF that uses `slingshot 10` and `libfabric/1.11.0.4.125`. I try to do a simple client-> server msg transfer using [Mercury](https://github.com/mercury-hpc/mercury) with verbs. Everything goes fine when the client scale <= 64 procs on 16 nodes. I tried to changes the server scale from 8 procs on 2 nodes to 4 procs on 1 node. But it doesn't work, so server scale is excluded from the reason. I tried 60 client procs on 15 nodes, it works fine. So 64(16) scale is the starting point of this problem. I also tried 72(18) scale to make sure this problem is not specific to 64(16) scale.

**To Reproduce**
It has too many software stacks, but generally the timeout happens in the simple [HG_Forward()](https://github.com/mercury-hpc/mercury/blob/master/src/mercury.h#L921)

**Expected behavior**
I expect the program just working for the scale above 64 procs on 16 nodes.

**Output**
I did a `export FI_LOG_LEVEL=warn` to see the logs. I found that when everything works fine, e.g. on the 60(15) scale, the log only has these 2 entries:
```
libfabric:27450:ofi_rxm:av:util_verify_av_attr():486<warn> Shared AV is unsupported
libfabric:27450:ofi_rxm:core:rxm_ep_sar_init():2608<warn> Requsted SAR limit (0) less or equal Eager limit (448). SAR limit won't be used. Messages of size <= SAR limit would be transmitted via Inject/Eager protocol. Messages of size > SAR limit would be transmitted via Rendezvous protocol
```

But when the timeout emerges, the log adds one more entry:
`libfabric:38582:verbs:fabric:vrb_get_matching_info():1523<warn> hints->ep_attr->rx_ctx_cnt != FI_SHARED_CONTEXT. Skipping XRC FI_EP_MSG endpoints`

So I assume this is the reason that Mercury stack is keep re-trying and finally gives out a timeout err.
Under @soumagne 's suggest, I set 

```
export NA_OFI_OP_RETRY_TIMEOUT=480000
export NA_OFI_OP_RETRY_PERIOD=1000
export FI_OFI_RXM_USE_SRX=1
```
But it still doesn't help.

**Environment:**
Polaris at ALCF, slingshot 10

```
bz186@polaris-login-01:~> cat /etc/os-release
NAME="SLES"
VERSION="15-SP3"
VERSION_ID="15.3"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP3"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp3"
DOCUMENTATION_URL="https://documentation.suse.com/"
```
Each node has 2 NICs, so the following info has the same thing for `mlx5_1`
```
bz186@x3005c0s1b0n0:~> fi_info -p verbs
provider: verbs
    fabric: IB-0xfe80000000000000
    domain: mlx5_0
    version: 111.0
    type: FI_EP_MSG
    protocol: FI_PROTO_RDMA_CM_IB_RC
provider: verbs
    fabric: IB-0xfe80000000000000
    domain: mlx5_0-dgram
    version: 111.0
    type: FI_EP_DGRAM
    protocol: FI_PROTO_IB_UD
provider: verbs;ofi_rxm
    fabric: IB-0xfe80000000000000
    domain: mlx5_0
    version: 111.0
    type: FI_EP_RDM
    protocol: FI_PROTO_RXM
```

**Additional context**

**Comment by shefty** [comment] 2023-02-10 01:51
Is libfabric 1.11.0.4.125 what ships with SUSE? In any case, 1.11 is fairly old at this point,  Are you able to retest with v1.17, so we can determine if the problem persists in a newer version?

**Comment by Zhang690683220** [comment] 2023-02-10 02:58
I think it is shipped with the entire cray environment.

```
bz186@polaris-login-01:~/dspaces/install/bin> module list

Currently Loaded Modules:
  1) craype-x86-rome          4) perftools-base/22.05.0   7) cray-dsmml/0.2.2   10) cray-pmi-lib/6.0.17  13) PrgEnv-nvhpc/8.3.3
  2) libfabric/1.11.0.4.125   5) nvhpc/21.9               8) cray-mpich/8.1.16  11) cray-pals/1.1.7      14) craype-accel-nvidia80
  3) craype-network-ofi       6) craype/2.7.15            9) cray-pmi/6.1.2     12) cray-libpals/1.1.7

```

I'm not sure if installing my own libfabric1.17 will make other stuff compatible but I'll give it a try.

**Comment by Zhang690683220** [comment] 2023-02-10 06:05
OK. It seems I cannot easily install the libfabric 1.17 and make all the software stack working since cray-mpich has the dependency on libfabric as well. But I just find setting `FI_VERBS_PREFER_XRC=0` makes everything work now.

The man page said

```
FI_OFI_RXM_USE_SRX
           This is a verbs;ofi_rxm libfabric ENV variable. Set this to 1 to instruct the provider to use shared
           receive queues. Using shared receive queues can reduce the overall memory usage significantly, but may
           cause latency to increase slightly. Only applies to Slingshot 10.

           Default behavior if unset:

                For jobs sizes of < 64 ranks, default is 0
                For job sizes of 64 ranks or larger, default is 1

       FI_VERBS_PREFER_XRC
           This is a verbs;ofi_rxm libfabric ENV variable. Set this to 1 to request use of the XRC (eXtended Reliable
           Connection) protocol. Note FI_OFI_RXM_USE_SRX must also be set to 1 when requesting XRC. Using the XRC
           protocol reduces the number of connections, hardware resources, and memory footprint for large scaling
           jobs that require a demanding communication pattern. This environment variable is required when scaling
           jobs with an all-to-all communication pattern. Only applies to Slingshot 10.

           Default behavior if unset:

                For jobs sizes of < 64 ranks, default is 0
                For job sizes of 64 ranks or larger, default is 1
```

So maybe there is something wrong when FI_VERBS_PREFER_XRC=1. But since libfaric 1.11 is outdated, I'm not sure if this is still a problem in the latest version

**Comment by shefty** [comment] 2023-02-10 16:58
Cray/HPE provided the XRC implementation and are the only ones that have tested it that I'm aware of.  The man page comments indicate that this is a vendor derivative of libfabric and not from the upstream release.    I would request assistance from HPE.  It may be a simple repackaging of v1.11, but HPE would need to confirm whether that's the case.

**Comment by thomasgillis** [comment] 2023-08-24 21:51
FWIW, I have similar issues with `libfabric 1.18.x`.
I have observed that it only depends on setting `FI_OFI_RXM_USE_SRX`. Just using `FI_VERBS_PREFER_XRC` works fine (but it doesn't do anything I presume).

When looking at the output, I get an error from `rxm` when trying to setup `FI_SHARED_CONTEXT`:
```
[1] libfabric:1100077:1692913375::ofi_rxm:core:ofi_check_ep_attr():731<info> Shared rx context not supported
```
but then later `verbs` is complaining about no shared rx context:
```
[1] libfabric:1100077:1692913375::verbs:fabric:vrb_get_matching_info():1541<warn> hints->ep_attr->rx_ctx_cnt != FI_SHARED_CONTEXT. Skipping XRC FI_EP_MSG endpoints
```

**Comment by swelch** [comment] 2023-08-24 22:05
@thomasgillis correct, XRC requires that RXM is using shared receive queue (SRX)

**Comment by shefty** [comment] 2023-08-24 22:05
FI_VERBS_PREFER_XRC will try to use XRC QPs, if available.  Slingshot 10 should have that feature.  HPE added xrc support, I believe, specifically for slingshot 10.  The use of XRC is not related to the scale.  It theoretically allows the scale to be higher than it would be if RC QPs are used.

The log messages produced from fi_getinfo are usually not errors relative to the higher-level application flow.  You would need to look at the surrounding messages.  The man page output above is something HPE added and is not upstream.  The text suggests that at least that version of libfabric has other changes to the rxm;verbs providers that are also not upstream.

@thomasgillis - I don't know if you're problems are related to using slingshot and HPE's software stack or not, or if you have some unrelated problem.  If you're getting as far as calling fi_write(), it sounds like you do have communication between nodes working.  You would have needed to in order to exchange the RMA address + keys.  fi_write() does not generate a completion at the target.

**Comment by thomasgillis** [comment] 2023-08-24 22:08
@shefty I am not using HPE stack, it's an IB network so maybe it explains why it doesn't work then?

Also, I forgot to mention that my `fi_write` has cqdata which is the one I never get on the target side.

**Comment by swelch** [comment] 2023-08-24 22:22
@thomasgillis if I recall correctly, a mofed revision resulted in a failure creating one of the needed objects, maybe the SRQ. A fix was added but you would need to look in the git history to see what version the fix went in and where it was back ported. XRC does not require the HPE stack, but it probably has the last validated version. Unless your noted is very old, you may need the fix. @muttormark my know what revision is required.

**Comment by thomasgillis** [comment] 2023-08-24 22:53
Sounds good, thx Steve :-)

**Comment by j-xiong** [comment] 2024-03-27 22:53
If I read correctly the issue is resolved.  Closing.

**Closed by j-xiong** 2024-03-27 22:53 UTC
Labels: bug
