### ISSUE TITLE
EFA: Multiple OSU benchmark crashes with recent libfabric versions

### ISSUE THREAD

**Issue by WilliamDowns** [ofiwg/libfabric#6698] opened 2021-04-20 16:32 UTC
### Background
In attempting to diagnose #6618 / [https://github.com/GEOS-ESM/MAPL/issues/739](https://github.com/GEOS-ESM/MAPL/issues/739), I tested many different MPI + libfabric version combinations to figure out when extra dedicated output servers were required to run the model (without hanging or crashing) on AWS ParallelCluster. Output servers have never previously been necessary when running GCHP (which uses MAPL) on other clusters / fabric setups in runs ranging from 36 to 1152 cores. Using the extra oservers increases cost to users both by requiring extra nodes (0 to 4 depending on resolution / diagnostic count per my testing) and increasing model runtime (I found that the output time increases slightly when using Intel MPI + oservers compared to just using TCP, but it increases 5-10x when using OpenMPI + oservers), so avoiding this requirement is very desirable. 

In my tests on AWS, I found that a crash or hang occurs at output time in the model in `MPI_Win_fence` when using `FI_PROVIDER=EFA` and libfabric version 1.12.1. This is true for both Intel MPI (tested 2019 U5 through U10) and OpenMPI 4.1.0. I tried using a few other libfabric versions between 1.9.0 and 1.12.1. For 1.9.0 only, I found that using OpenMPI + EFA works in the model without the need for oservers. I was unable to run the model beyond initialization with libfabric 1.9.0 and Intel MPI + EFA. 

If I use `FI_PROVIDER=TCP`, the model completes perfectly with no oserver with OpenMPI for both libfabric 1.12.1 and 1.9.0. For Intel MPI + TCP + libfabric 1.12.1, I am able to use more output diagnostics and increase model resolution without crashing compared to when using EFA. If I use Intel MPI + TCP + libfabric 1.9.0, I am able to achieve even greater numbers of diagnostics and higher model resolution (equivalent to OpenMPI + TCP). 

More details of my model testing are available at [https://github.com/GEOS-ESM/MAPL/issues/739#issuecomment-821301026](https://github.com/GEOS-ESM/MAPL/issues/739#issuecomment-821301026).

### Microbenchmark results
Given my model hangs / crashes consistently occur in `MPI_Win_fence`, I decided to run some OSU microbenchmarks that have options for extra calls to `MPI_Win_fence`. I tested:

- osu_put_latency
- osu_get_latency
- osu_put_bw
- osu_get_bw
- osu_put_bibw
- osu_acc_latency
- osu_cas_latency
- osu_fop_latency
- osu_get_acc_latency

 with and without their extra `-s fence` options for each of my MPI + libfabric setups. 

My installation + run setup consisted of:

```
spack install osu-micro-benchmarks ^openmpi@4.1.0 +pmi fabrics=ofi schedulers=slurm +legacylaunchers ^libfabric@1.12.1 fabrics=efa,shm
spack install osu-micro-benchmarks ^openmpi@4.1.0 +pmi fabrics=ofi schedulers=slurm +legacylaunchers ^libfabric@1.9.0 fabrics=efa,shm
spack install osu-micro-benchmarks +ofi ^intel-mpi@2019.10.317 ^libfabric@1.12.1 fabrics=efa,shm #had to add a libfabric build dependency to osu-micro-benchmarks to ensure proper linking with libfabric (although Intel's internal 1.11.0 libfabric yielded the same results as libfabric 1.12.1)
spack install osu-micro-benchmarks +ofi ^intel-mpi@2019.10.317 ^libfabric@1.9.0 fabrics=efa,shm

#1 run on 1 node example
spack load osu-micro-benchmarks^intel-mpi^libfabric@1.12.1
export FI_PROVIDER=efa
mpirun -np 2 $(spack location -i osu-micro-benchmarks ^intel-mpi ^libfabric@1.12.1)/libexec/osu-micro-benchmarks/mpi/one-sided/osu_put_latency
mpirun -np 2 $(spack location -i osu-micro-benchmarks ^intel-mpi ^libfabric@1.12.1)/libexec/osu-micro-benchmarks/mpi/one-sided/osu_put_latency -s fence
```

I found that when running across 2 nodes, all tests complete perfectly for each MPI (Intel MPI 2019 U10, OpenMPI 4.1.0), libfabric version (1.12.1, 1.9.0), and fabric provider (EFA, TCP). 

When running on 1 node, no issues occur when using TCP and any MPI / libfabric. When using Intel MPI + libfabric 1.12.1 +EFA, I run into segfaults for osu_acc_latency, osu_cas_latency, osu_fop_latency, and osu_get_acc_latency. Example output from osu_acc_latency:

```
# OSU MPI_Accumulate latency Test v5.7
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_flush
# Size          Latency (us)

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 16303 RUNNING AT compute-dy-c5n18xlarge-3
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 16304 RUNNING AT compute-dy-c5n18xlarge-3
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
```

When using OpenMPI + libfabric 1.12.1 + EFA on 1 node, I get a segfault only in osu_cas_latency.

When using libfabric 1.9.0 + EFA + either MPI, I encounter no errors.

**Comment by shijin-aws** [comment] 2021-04-20 17:01
Thank you for your detailed report, we are looking at it.

**Comment by shijin-aws** [comment] 2021-04-20 20:18
Hi, I installed libfabric 1.12.1, Intel MPI 2019 U10, and osu-micro-benchmarks 5.7. But I was not able to reproduce the segfault. I ran my tests on 1 c5n.18xlarge and tried with and without `-s fence` option:

```
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_acc_latency
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Accumulate latency Test v5.7
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_flush
# Size          Latency (us)
1                       0.79
2                       0.79
4                       0.79
8                       0.80
16                      0.79
32                      0.79
64                      0.80
128                     0.80
256                     0.81
512                     0.82
1024                    0.84
2048                    0.88
4096                    0.96
8192                    1.11
16384                   1.49
32768                   2.11
65536                   3.41
131072                  5.89
262144                 10.92
524288                 23.53
1048576                80.20
2097152               158.91
4194304               317.47
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_acc_latency -s fence
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Accumulate latency Test v5.7
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_fence
# Size          Latency (us)
1                       3.24
2                       2.90
4                       2.82
8                       2.82
16                      2.82
32                      2.81
64                      2.73
128                     2.67
256                     2.75
512                     2.74
1024                    2.77
2048                    2.93
4096                    2.88
8192                    3.11
16384                   3.50
32768                   4.15
65536                   5.49
131072                  8.14
262144                 13.78
524288                 28.08
1048576                83.62
2097152               163.42
4194304               324.48
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_cas_latency -s fence
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Compare_and_swap latency Test v5.7
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_fence
# Size          Latency (us)
8                       2.88
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_cas_latency
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Compare_and_swap latency Test v5.7
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_flush
# Size          Latency (us)
8                       0.81
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_cas_latency -s fence
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Compare_and_swap latency Test v5.7
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_fence
# Size          Latency (us)
8                       2.88
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_fop_latency
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Fetch_and_op latency Test v5.7
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_flush
# Size          Latency (us)
8                       0.78
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_fop_latency -s fence
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Fetch_and_op latency Test v5.7
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_fence
# Size          Latency (us)
8                       2.93
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_get_acc_latency
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Get_accumulate latency Test v5.7
# Window creation: MPI_Win_create
# Synchronization: MPI_Win_lock/unlock
# Size          Latency (us)
1                       4.15
2                       3.79
4                       3.59
8                       3.52
16                      3.52
32                      3.52
64                      3.54
128                     3.66
256                     4.32
512                     4.32
1024                    4.38
2048                    4.85
4096                    5.79
8192                    7.30
16384                  10.25
32768                  17.08
65536                  28.58
131072                 50.15
262144                 96.13
524288                237.16
1048576               512.23
2097152              1016.27
4194304              2024.25
[ec2-user@ip-172-31-9-144 fsx]$ mpirun -np 2 -f /fsx/hfile /fsx/omb/impi-u10/libexec/osu-micro-benchmarks/mpi/one-sided/osu_get_acc_latency -s fence
[0] MPI startup(): Intel(R) MPI Library, Version 2019 Update 10  Build 20210120 (id: d7908565b)
[0] MPI startup(): Copyright (C) 2003-2021 Intel Corporation.  All rights reserved.
[0] MPI startup(): library kind: release
[0] MPI startup(): libfabric version: 1.12.1
[0] MPI startup(): libfabric provider: efa
# OSU MPI_Get_accumulate latency Test v5.7
# Window creation: MPI_Win_create
# Synchronization: MPI_Win_fence
# Size          Latency (us)
1                       3.58
2                       3.31
4                       3.26
8                       3.27
16                      3.26
32                      3.27
64                      3.26
128                     3.30
256                     3.71
512                     3.98
1024                    4.23
2048                    4.50
4096                    5.69
8192                    7.10
16384                   9.84
32768                  16.06
65536                  28.42
131072                 50.62
262144                129.31
524288                252.77
1048576               518.41
2097152              1023.37
4194304              2223.02
```

I tried to install all the softwares above with spack using the same command you were using, with spack's develop branch, but I hit errors:

```
[ec2-user@ip-172-31-9-144 spack]$ spack install osu-micro-benchmarks +ofi ^intel-mpi@2019.10.317 ^libfabric@1.12.1 fabrics=efa,shm
==> Error: trying to set variant "ofi" in package "osu-micro-benchmarks", but the package has no such variant [happened during concretization of osu-micro-benchmarks+ofi]
```
Could you share the version of spack you were using? It seems you were using aws-parallelcluster. Could you share the parallel cluster version and the `base_os`?

**Comment by WilliamDowns** [comment] 2021-04-20 20:28
Thanks for testing. I had to add the `ofi` variant (to make the benchmarks build with links to the correct fabric providers) to the osu-micro-benchmarks package in Spack (on the develop branch) by adding the following lines to `$SPACK_ROOT/var/spack/repos/builtin/packages/osu-micro-benchmarks/package.py`:

```
    variant('cuda', default=False, description="Enable CUDA support")
    variant('ofi', default=False, description="Enable explicit libfabric support") #add this
    depends_on('mpi')
    depends_on('cuda', when='+cuda')
    depends_on('libfabric', when='+ofi') #add this

```

I'm using ParallelCluster 2.10.1 with centos7.

**Comment by shijin-aws** [comment] 2021-04-20 20:32
Thanks. I was using amazon linux2, I will try centos7 and reproduce it.

**Comment by shijin-aws** [comment] 2021-04-20 21:46
Hi, I hit this error when using spack to install the softwares

```
[centos@ip-172-31-11-132 spack]$ spack install osu-micro-benchmarks +ofi ^intel-mpi@2019.10.317 ^libfabric@1.12.1 fabrics=efa,shm
...

[+] /fsx/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/libfabric-1.12.1-idznjje2mtrgi5wfe7kzn4g4rubo5olw
==> Installing osu-micro-benchmarks-5.7-6gffb5rnyddwzfkfefzvojmpvoihp7b6
==> Warning: Spack will not check SSL certificates. You need to update your Python to enable certificate verification.
==> No binary for osu-micro-benchmarks-5.7-6gffb5rnyddwzfkfefzvojmpvoihp7b6 found: installing from source
==> Error: AttributeError: 'module' object has no attribute 'sbang'

/fsx/spack/lib/spack/spack/build_environment.py:930, in _setup_pkg_and_run:
        927        tb_string = traceback.format_exc()
        928
        929        # build up some context from the offending package so we can
  >>    930        # show that, too.
        931        package_context = get_package_context(tb)
        932
        933        logfile = None
```

Also could you share how did you install gcc 9.3.0? Pcluster's centos7 AMI only has gcc 4.8.5.

**Comment by WilliamDowns** [comment] 2021-04-21 14:24
Just tested several more configurations on my end:

- Spack-built OSUMB (gcc@9.3.0)+ ParallelCluster's built-in Intel MPI and libfabric (2019 U8 and 1.11.1): segfaults
- Spack-built OSUMB (gcc@9.3.0) + Intel MPI 2019 U9: no segfaults
- Spack-built OSUMB + Intel Compilers (2021.2) + Intel MPI 2019 U10: no segfaults
- Manual-built OSUMB + Spack-built Intel MPI 2019 U10 (gcc@9.3.0): no segfaults
- Manual-built OSUMB + built-in IMPI and libfabric: no segfaults

So not sure what the common thread is here.

Regarding building with gcc 9.3.0, this should be how I did it:

```
spack install gcc@9.3.0
spack compiler find $(spack location -i gcc@9.3.0)
spack install osu-micro-benchmarks%gcc@9.3.0 +ofi ^intel-mpi@2019.10.317 ^libfabric@1.12.1 fabrics=efa,shm
```

**Comment by WilliamDowns** [comment] 2021-04-21 15:17
Just did a test with Manual-built OSUMB + gcc 9.3.0 + Spack-built OpenMPI  4.1.0 + libfabric 1.12.1 and got the following error in osu_cas_latency (which, after checking my logs, I also ran into with yesterday's Spack-built equivalent run):
```
[compute-dy-c5n18xlarge-1:00726] *** Process received signal ***
[compute-dy-c5n18xlarge-1:00726] Signal: Segmentation fault (11)
[compute-dy-c5n18xlarge-1:00726] Signal code: Address not mapped (1)
[compute-dy-c5n18xlarge-1:00726] Failing at address: (nil)
[compute-dy-c5n18xlarge-1:00726] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7f64d7db1630]
[compute-dy-c5n18xlarge-1:00726] [ 1] /home/centos/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/openmpi-4.1.0-4aigxbuj2xvmr4bqzsm6tske3wtpsa7c/lib/libopen-pal.so.40(mca_btl_ofi_acswap+0xc0)[0x7f64d70ded40]
[compute-dy-c5n18xlarge-1:00726] [ 2] /home/centos/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/openmpi-4.1.0-4aigxbuj2xvmr4bqzsm6tske3wtpsa7c/lib/libmpi.so.40(ompi_osc_rdma_compare_and_swap+0x4df)[0x7f64d8a922bf]
[compute-dy-c5n18xlarge-1:00726] [ 3] /home/centos/spack/opt/spack/linux-centos7-skylake_avx512/gcc-9.3.0/openmpi-4.1.0-4aigxbuj2xvmr4bqzsm6tske3wtpsa7c/lib/libmpi.so.40(PMPI_Compare_and_swap+0xe6)[0x7f64d894f436]
[compute-dy-c5n18xlarge-1:00726] [ 4] /shared/osu_benchmarking/april/non-spack/openmpi/libexec/osu-micro-benchmarks/mpi/one-sided/osu_cas_latency[0x4022f0]
[compute-dy-c5n18xlarge-1:00726] [ 5] /shared/osu_benchmarking/april/non-spack/openmpi/libexec/osu-micro-benchmarks/mpi/one-sided/osu_cas_latency[0x402070]
[compute-dy-c5n18xlarge-1:00726] [ 6] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f64d79f6555]
[compute-dy-c5n18xlarge-1:00726] [ 7] /shared/osu_benchmarking/april/non-spack/openmpi/libexec/osu-micro-benchmarks/mpi/one-sided/osu_cas_latency[0x4020c5]
[compute-dy-c5n18xlarge-1:00726] *** End of error message ***
srun: error: compute-dy-c5n18xlarge-1: task 0: Segmentation fault (core dumped)
```

I also did a run with manual-built OSUMB + built-in OpenMPI (4.1.0) and got no segfaults. So again a Spack-specific issue (though seemingly not quite the same as the Intel MPI issues since the above OpenMPI failure occurred with manual-built benchmarks + Spack-built MPI rather than in Spack-built benchmarks).

**Comment by wzamazon** [comment] 2021-07-12 14:04
@WilliamDowns Since this is a spack specific issue. I am going to close it.

**Closed by wzamazon** 2021-07-12 14:04 UTC
Labels: prov/EFA
